'use client';

import katex from 'katex';
import { FormEvent, useEffect, useMemo, useState } from 'react';

type View = 'reader' | 'library' | 'graph' | 'discover' | 'notes' | 'settings';
type ReaderMode = 'source' | 'guide';
type Paper = { id: string; title: string; authors: string; category: string; arxivId: string; abstract: string; state: 'To read' | 'Reading' | 'Read'; tags: string[]; folder?: string };
type Profile = { level: string; area: string; goal: string; model: string; reasoning: string };
type Note = { id: string; paperId: string; nodeId: string; anchor: string; text: string; latex: string; createdAt: string };
type Anchor = { label: string; page: number | null; confidence: 'verified' | 'approximate' | 'unverified' };
type NodeKind = 'definition' | 'assumption' | 'notation' | 'lemma' | 'proposition' | 'theorem' | 'corollary' | 'proof' | 'equation' | 'remark' | 'example' | 'section' | 'external-result';
type AuditNode = { id: string; kind: NodeKind; label: string; title: string; statement: string; status: 'verified' | 'needs-verification' | 'unavailable'; anchor: Anchor; role: string; dependencies: string[]; proofSketch: string[]; whyItMatters: string; expandable: boolean };
type CrossLink = { id: string; from: { paperId: string; nodeId: string }; to: { paperId: string; nodeId: string }; relation: 'uses' | 'extends' | 'background' | 'contrasts'; note: string; source: 'manual' | 'audit'; createdAt?: string };
type AuditCrossLink = { fromNodeId: string; targetPaperId: string; targetNodeId: string; relation: CrossLink['relation']; rationale: string };
type PaperAudit = { threadId: string; generatedAt: string; rawText: string; audit: { sourceStatus: 'full-text-read' | 'partial-text-read' | 'blocked'; sourceSummary: string; centralQuestion: string; mainContribution: string; verificationWarnings: string[] }; nodes: AuditNode[]; readingPaths: { goal: string; nodeIds: string[]; reason: string }[]; crossPaperLinks: AuditCrossLink[]; openQuestions: string[] };
type GraphNode = { id: string; paperId: string; paperTitle: string; arxivId: string; nodeId: string; label: string; title: string; kind: NodeKind; page: number | null; status: AuditNode['status'] };
type GraphEdge = { id: string; from: string; to: string; relation: CrossLink['relation']; source: 'manual' | 'audit'; note?: string };
type Graph = { version: number; updatedAt: string | null; nodes: GraphNode[]; edges: GraphEdge[] };
type Bridge = { running: boolean; account: { type: string; planType: string | null } | null; models: { id: string; label: string; efforts: string[]; defaultEffort: string | null; isDefault: boolean }[]; lastError: string | null };
type VaultSnapshot = { papers: Paper[]; audits: Record<string, PaperAudit>; notes: Note[]; nodeNotes: Record<string, Record<string, string>>; nodeAnswers: Record<string, Record<string, string>>; expanded: Record<string, Record<string, boolean>>; profile: Profile | null; links: CrossLink[]; graph: Graph; vault: { paperFolders: { paperId: string; folder: string }[] } };

const bridgeUrl = 'http://127.0.0.1:4318';
const preferenceKey = 'proofroom-reader-preferences-v1';
const defaultProfile: Profile = { level: 'Graduate student', area: 'math.AP', goal: 'Understand proofs', model: '', reasoning: 'medium' };
const emptyGraph: Graph = { version: 1, updatedAt: null, nodes: [], edges: [] };
const fallbackDiscoveries: Paper[] = [
  { id: 'd-1', title: 'Stability estimates for degenerate elliptic equations', authors: 'E. Moreno', category: 'math.AP', arxivId: '2608.05192', abstract: 'New stability estimates that extend compactness methods to a degenerate setting.', state: 'To read', tags: ['elliptic PDE', 'stability'] },
  { id: 'd-2', title: 'Geodesic convexity in spaces of probability measures', authors: 'N. Berg · K. Ito', category: 'math.OC', arxivId: '2608.05014', abstract: 'A concise treatment of geodesic convexity and its variational consequences.', state: 'To read', tags: ['optimal transport', 'convexity'] },
];

function Latex({ value, small = false }: { value: string; small?: boolean }) {
  const html = useMemo(() => katex.renderToString(value || '\\text{Add a LaTeX formula}', { throwOnError: false, strict: 'ignore', displayMode: true }), [value]);
  return <div className={`${small ? 'text-sm' : 'text-base'} overflow-x-auto text-[#284235]`} dangerouslySetInnerHTML={{ __html: html }} />;
}

function readString(value: unknown, fallback = '') { return typeof value === 'string' ? value : fallback; }
function asArray(value: unknown) { return Array.isArray(value) ? value : []; }
function parseAudit(rawText: string, threadId: string): PaperAudit {
  const clean = rawText.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
  const first = clean.indexOf('{'); const last = clean.lastIndexOf('}');
  if (first < 0 || last <= first) throw new Error('Codex returned no structured audit. Try again.');
  const data = JSON.parse(clean.slice(first, last + 1)) as Record<string, unknown>;
  const auditData = data.audit as Record<string, unknown> | undefined;
  if (!auditData || !Array.isArray(data.nodes)) throw new Error('Codex returned an incomplete audit. Try again.');
  const kinds = new Set<NodeKind>(['definition', 'assumption', 'notation', 'lemma', 'proposition', 'theorem', 'corollary', 'proof', 'equation', 'remark', 'example', 'section', 'external-result']);
  const statuses = new Set<AuditNode['status']>(['verified', 'needs-verification', 'unavailable']);
  const sourceStatus = new Set<PaperAudit['audit']['sourceStatus']>(['full-text-read', 'partial-text-read', 'blocked']);
  const confidence = new Set<Anchor['confidence']>(['verified', 'approximate', 'unverified']);
  return {
    threadId,
    generatedAt: new Date().toISOString(),
    rawText,
    audit: {
      sourceStatus: sourceStatus.has(auditData.sourceStatus as PaperAudit['audit']['sourceStatus']) ? auditData.sourceStatus as PaperAudit['audit']['sourceStatus'] : 'partial-text-read',
      sourceSummary: readString(auditData.sourceSummary, 'No source summary returned.'),
      centralQuestion: readString(auditData.centralQuestion, 'Not established.'),
      mainContribution: readString(auditData.mainContribution, 'Not established.'),
      verificationWarnings: asArray(auditData.verificationWarnings).map(String),
    },
    nodes: data.nodes.map((item, index): AuditNode => {
      const entry = item as Record<string, unknown>; const anchor = entry.anchor as Record<string, unknown> | undefined;
      return { id: readString(entry.id, `unit-${index + 1}`), kind: kinds.has(entry.kind as NodeKind) ? entry.kind as NodeKind : 'section', label: readString(entry.label, `Unit ${index + 1}`), title: readString(entry.title, readString(entry.label, `Unit ${index + 1}`)), statement: readString(entry.statement), status: statuses.has(entry.status as AuditNode['status']) ? entry.status as AuditNode['status'] : 'needs-verification', anchor: { label: readString(anchor?.label, 'Source location unavailable'), page: typeof anchor?.page === 'number' ? anchor.page : null, confidence: confidence.has(anchor?.confidence as Anchor['confidence']) ? anchor?.confidence as Anchor['confidence'] : 'unverified' }, role: readString(entry.role), dependencies: asArray(entry.dependencies).map(String), proofSketch: asArray(entry.proofSketch).map(String), whyItMatters: readString(entry.whyItMatters), expandable: Boolean(entry.expandable) };
    }),
    readingPaths: asArray(data.readingPaths).map((item) => { const path = item as Record<string, unknown>; return { goal: readString(path.goal, 'Reading path'), nodeIds: asArray(path.nodeIds).map(String), reason: readString(path.reason) }; }),
    crossPaperLinks: asArray(data.crossPaperLinks).map((item) => { const link = item as Record<string, unknown>; const relation = ['uses', 'extends', 'background', 'contrasts'].includes(readString(link.relation)) ? readString(link.relation) as CrossLink['relation'] : 'uses'; return { fromNodeId: readString(link.fromNodeId), targetPaperId: readString(link.targetPaperId), targetNodeId: readString(link.targetNodeId), relation, rationale: readString(link.rationale) }; }).filter((link) => link.fromNodeId && link.targetPaperId && link.targetNodeId),
    openQuestions: asArray(data.openQuestions).map(String),
  };
}

function kindClass(kind: NodeKind) { if (kind === 'theorem' || kind === 'corollary') return 'bg-[#295e49] text-white'; if (kind === 'lemma' || kind === 'proposition') return 'bg-[#dceee1] text-[#286448]'; if (kind === 'definition' || kind === 'notation' || kind === 'assumption') return 'bg-[#e5edf7] text-[#3c6390]'; return 'bg-[#f4eee7] text-[#816552]'; }
function auditLabel(status: PaperAudit['audit']['sourceStatus']) { return status === 'full-text-read' ? 'Full text audited' : status === 'partial-text-read' ? 'Partial source audit' : 'Source access blocked'; }
function unitId(paperId: string, nodeId: string) { return `${paperId}::${nodeId}`; }

export default function Home() {
  const [view, setView] = useState<View>('reader');
  const [papers, setPapers] = useState<Paper[]>([]);
  const [audits, setAudits] = useState<Record<string, PaperAudit>>({});
  const [notes, setNotes] = useState<Note[]>([]);
  const [nodeNotes, setNodeNotes] = useState<Record<string, Record<string, string>>>({});
  const [nodeAnswers, setNodeAnswers] = useState<Record<string, Record<string, string>>>({});
  const [expanded, setExpanded] = useState<Record<string, Record<string, boolean>>>({});
  const [, setLinks] = useState<CrossLink[]>([]);
  const [graph, setGraph] = useState<Graph>(emptyGraph);
  const [profile, setProfile] = useState<Profile>(defaultProfile);
  const [discoveries, setDiscoveries] = useState<Paper[]>(fallbackDiscoveries);
  const [selectedPaperId, setSelectedPaperId] = useState('');
  const [selectedNodeId, setSelectedNodeId] = useState('');
  const [importing, setImporting] = useState(false);
  const [analysingId, setAnalysingId] = useState<string | null>(null);
  const [askingId, setAskingId] = useState<string | null>(null);
  const [bridge, setBridge] = useState<Bridge | null>(null);
  const [vaultReady, setVaultReady] = useState(false);
  const [loadingDiscoveries, setLoadingDiscoveries] = useState(false);
  const [notice, setNotice] = useState('');

  const paper = papers.find((item) => item.id === selectedPaperId) ?? papers[0];
  const audit = paper ? audits[paper.id] : undefined;
  const node = audit?.nodes.find((item) => item.id === selectedNodeId) ?? audit?.nodes[0];

  function notify(message: string) { setNotice(message); window.setTimeout(() => setNotice(''), 4500); }
  function applySnapshot(snapshot: VaultSnapshot) {
    setPapers(snapshot.papers); setAudits(snapshot.audits); setNotes(snapshot.notes); setNodeNotes(snapshot.nodeNotes); setNodeAnswers(snapshot.nodeAnswers); setExpanded(snapshot.expanded); setLinks(snapshot.links); setGraph(snapshot.graph ?? emptyGraph);
    if (snapshot.profile) setProfile({ ...defaultProfile, ...snapshot.profile });
    setSelectedPaperId((current) => snapshot.papers.some((item) => item.id === current) ? current : snapshot.papers[0]?.id ?? '');
  }
  async function refreshBridge() { try { const response = await fetch(`${bridgeUrl}/status`); const data = await response.json() as Bridge; setBridge(data); if (data.models?.length) setProfile((current) => data.models.some((item) => item.id === current.model) ? current : { ...current, model: data.models.find((item) => item.isDefault)?.id ?? '' }); } catch { setBridge(null); } }
  async function loadVault() { try { const response = await fetch(`${bridgeUrl}/vault`); if (!response.ok) throw new Error(); applySnapshot(await response.json() as VaultSnapshot); } catch { const saved = localStorage.getItem(preferenceKey); if (saved) { try { setProfile({ ...defaultProfile, ...JSON.parse(saved) }); } catch {} } } finally { setVaultReady(true); } }
  useEffect(() => {
    const timer = window.setTimeout(() => { void loadVault(); void refreshBridge(); }, 0);
    return () => window.clearTimeout(timer);
    // The bridge functions intentionally run once when this local reader mounts.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => {
    if (!paper || !audit || audit.nodes.some((item) => item.id === selectedNodeId)) return;
    const timer = window.setTimeout(() => setSelectedNodeId(audit.nodes[0]?.id ?? ''), 0);
    return () => window.clearTimeout(timer);
  }, [paper, audit, selectedNodeId]);
  useEffect(() => { localStorage.setItem(preferenceKey, JSON.stringify(profile)); if (vaultReady) void fetch(`${bridgeUrl}/vault/profile`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ profile }) }); }, [profile, vaultReady]);
  useEffect(() => {
    if (!vaultReady || !paper) return;
    const timer = window.setTimeout(() => { void fetch(`${bridgeUrl}/vault/reader`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paperId: paper.id, reader: { notes: notes.filter((item) => item.paperId === paper.id), nodeNotes: nodeNotes[paper.id] ?? {}, nodeAnswers: nodeAnswers[paper.id] ?? {}, expanded: expanded[paper.id] ?? {} } }) }); }, 500);
    return () => window.clearTimeout(timer);
  }, [vaultReady, paper, notes, nodeNotes, nodeAnswers, expanded]);

  async function savePaper(incoming: Paper) {
    const response = await fetch(`${bridgeUrl}/vault/paper`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper: incoming }) });
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not create the paper folder.');
    const stored = data.paper as Paper;
    setPapers((current) => [stored, ...current.filter((item) => item.id !== stored.id && item.arxivId !== stored.arxivId)]);
    return stored;
  }
  async function analyzePaper(target: Paper) {
    setAnalysingId(target.id);
    try {
      const response = await fetch(`${bridgeUrl}/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper: target, profile }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Local Codex analysis failed.');
      const stored = data.paper as Paper; const next = parseAudit(readString(data.text), readString(data.threadId));
      const saved = await fetch(`${bridgeUrl}/vault/audit`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper: stored, audit: next }) });
      const snapshot = await saved.json(); if (!saved.ok) throw new Error(snapshot.error || 'Could not save the local audit.');
      setPapers((current) => [snapshot.paper as Paper, ...current.filter((item) => item.id !== stored.id && item.arxivId !== stored.arxivId)]); setAudits((current) => ({ ...current, [stored.id]: next })); setGraph(snapshot.graph ?? emptyGraph); setLinks(snapshot.links ?? []); setSelectedPaperId(stored.id); setSelectedNodeId(next.nodes[0]?.id ?? ''); setView('reader'); notify(`${next.nodes.length} audited document units are ready.`); void refreshBridge();
    } catch (error) { notify(`${error instanceof Error ? error.message : 'Analysis failed.'} Start the local bridge and try again.`); void refreshBridge(); }
    finally { setAnalysingId(null); }
  }
  async function importArxiv(raw: string) {
    const response = await fetch(`/api/arxiv?id=${encodeURIComponent(raw)}`); const data = await response.json();
    if (!response.ok || !data.papers?.[0]) throw new Error('Paper not found on arXiv.');
    const incoming = { ...data.papers[0], state: 'Reading' } as Paper; const existing = papers.find((item) => item.arxivId === incoming.arxivId); setImporting(false); await analyzePaper(existing ?? incoming);
  }
  async function saveDiscovery(candidate: Paper) { try { const stored = await savePaper({ ...candidate, state: 'To read' }); setSelectedPaperId(stored.id); notify('Paper saved with its own local folder.'); } catch (error) { notify(error instanceof Error ? error.message : 'Could not save the paper.'); } }
  async function askNode(targetNode: AuditNode, question: string) { if (!audit?.threadId || !paper || !question.trim()) return; setAskingId(targetNode.id); try { const response = await fetch(`${bridgeUrl}/node-question`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper, profile, node: targetNode, question, threadId: audit.threadId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Codex did not answer this unit.'); setNodeAnswers((current) => ({ ...current, [paper.id]: { ...current[paper.id], [targetNode.id]: readString(data.text) } })); } catch (error) { notify(error instanceof Error ? error.message : 'The local Codex question failed.'); } finally { setAskingId(null); } }
  function saveNote(anchor: string, nodeId: string, text: string, latex: string) { if (!paper || !text.trim()) return; setNotes((current) => [{ id: `n-${Date.now()}`, paperId: paper.id, nodeId, anchor, text, latex, createdAt: 'just now' }, ...current]); notify('Linked note saved in this paper folder.'); }
  async function addLink(link: Omit<CrossLink, 'id' | 'source' | 'createdAt'>) { try { const response = await fetch(`${bridgeUrl}/vault/link`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ link }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not create the relation.'); setLinks((current) => current.some((item) => item.id === data.link.id) ? current : [...current, data.link]); setGraph(data.graph ?? emptyGraph); notify('Cross-paper relation added to the local graph.'); } catch (error) { notify(error instanceof Error ? error.message : 'Could not create the relation.'); } }
  async function removeLink(linkId: string) { const response = await fetch(`${bridgeUrl}/vault/link/delete`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ linkId }) }); const data = await response.json(); if (response.ok) { setLinks((current) => current.filter((item) => item.id !== linkId)); setGraph(data.graph ?? emptyGraph); } }
  async function refreshDiscoveries() { setLoadingDiscoveries(true); try { const response = await fetch(`/api/arxiv?category=${encodeURIComponent(profile.area)}`); const data = await response.json(); if (!response.ok || !data.papers?.length) throw new Error(); setDiscoveries(data.papers); } catch { notify('arXiv is unavailable right now; showing local examples.'); } finally { setLoadingDiscoveries(false); } }
  function openUnit(paperId: string, nodeId: string) { setSelectedPaperId(paperId); setSelectedNodeId(nodeId); setView('reader'); }

  return <main className="min-h-screen bg-[#f8f8f5] text-[#20251f] lg:grid lg:grid-cols-[54px_235px_minmax(0,1fr)]">
    <nav className="hidden min-h-screen flex-col items-center gap-2 border-r border-[#e0e4dd] bg-[#273b31] py-4 text-[#dfece4] lg:flex"><div className="mb-4 grid h-8 w-8 place-items-center rounded-lg bg-[#5b806d] text-[10px] font-black">PR</div>{([['reader', '⌁', 'Read'], ['library', '▦', 'Library'], ['graph', '⌘', 'Graph'], ['discover', '✦', 'Discover'], ['notes', '✎', 'Notes'], ['settings', '⚙', 'Settings']] as const).map(([target, icon, label]) => <button key={target} onClick={() => setView(target)} title={label} className={`grid h-9 w-9 place-items-center rounded-lg text-base ${view === target ? 'bg-[#476956] text-white' : 'hover:bg-[#3b5b49]'}`}>{icon}</button>)}<div className="flex-1" /><span title={bridge?.account ? 'Local Codex ready' : 'Local Codex unavailable'} className={`mb-2 h-2 w-2 rounded-full ${bridge?.account ? 'bg-[#75ca94]' : 'bg-[#d9b159]'}`} /></nav>
    <aside className="hidden min-h-screen flex-col border-r border-[#e2e6e0] bg-[#f0f2ed] p-4 lg:flex"><div className="flex items-start justify-between"><div><p className="text-[9px] font-extrabold uppercase tracking-[.13em] text-[#778078]">LOCAL VAULT</p><h1 className="mt-1 text-lg font-bold tracking-[-.04em]">Papers</h1></div><button onClick={() => setImporting(true)} className="grid h-7 w-7 place-items-center rounded-md border border-[#ccd5cc] text-lg text-[#426652]">+</button></div><button onClick={() => setImporting(true)} className="my-4 rounded-md bg-[#deebe1] px-3 py-2 text-left text-[11px] font-bold text-[#2d604b]">+ Import & audit arXiv paper</button><div className="mb-2 flex justify-between text-[10px] font-bold text-[#677068]"><span>YOUR LIBRARY</span><span>{papers.length}</span></div><div className="min-h-0 flex-1 space-y-1 overflow-y-auto">{papers.length ? papers.map((item) => <button key={item.id} onClick={() => { setSelectedPaperId(item.id); setView('reader'); }} className={`w-full rounded-lg p-2 text-left ${item.id === paper?.id && view === 'reader' ? 'bg-[#dfe9e0]' : 'hover:bg-[#e7ebe6]'}`}><span className="flex items-start gap-2"><i className={`mt-1 h-1.5 w-1.5 flex-none rounded-full ${audits[item.id] ? 'bg-[#499b70]' : 'bg-[#d6b756]'}`} /><span><b className="block text-[11px] leading-[1.35]">{item.title}</b><small className="mt-1 block text-[9px] text-[#788178]">{item.arxivId}</small>{item.folder && <small className="mt-1 block truncate font-mono text-[8px] text-[#8b948a]">{item.folder}</small>}</span></span></button>) : <p className="rounded-lg border border-dashed border-[#d5ddd5] p-3 text-[11px] leading-5 text-[#788178]">Your vault is empty. Import an arXiv paper to create its first folder.</p>}</div><button onClick={() => { setView('discover'); void refreshDiscoveries(); }} className="mt-3 flex items-center gap-2 border-t border-[#dce2db] pt-3 text-left"><span className="grid h-6 w-6 place-items-center rounded bg-[#e3eee6] text-[#327055]">◌</span><span><b className="block text-[10px]">Discover</b><small className="text-[9px] text-[#788078]">New arXiv papers</small></span></button></aside>
    <section className="min-w-0"><header className="flex h-12 items-center justify-between border-b border-[#e2e6e0] bg-white px-4 sm:px-6"><div className="min-w-0 truncate text-[11px] text-[#727b72]">{view === 'reader' && paper ? <><span className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-[#4a9b70]" />{paper.title}</> : view === 'graph' ? 'Local dependency graph' : view[0].toUpperCase() + view.slice(1)}</div><div className="flex items-center gap-2"><div className="hidden gap-1 sm:flex">{(['reader', 'library', 'graph', 'notes'] as View[]).map((item) => <button key={item} onClick={() => setView(item)} className={`rounded px-1.5 py-1 text-[10px] ${view === item ? 'font-bold text-[#285f49]' : 'text-[#7a837a]'}`}>{item}</button>)}</div><button onClick={() => setImporting(true)} className="rounded-md border border-[#d8e0d7] bg-white px-2.5 py-1.5 text-[10px] text-[#486552]">+ Import</button></div></header>{notice && <div className="border-b border-[#ecd9bb] bg-[#fff8ed] px-5 py-2 text-xs text-[#76552e]">{notice}</div>}
      {view === 'reader' && <Reader paper={paper} audit={audit} node={node} selectedNodeId={selectedNodeId} setSelectedNodeId={setSelectedNodeId} expanded={paper ? expanded[paper.id] ?? {} : {}} setExpanded={(id, value) => paper && setExpanded((current) => ({ ...current, [paper.id]: { ...current[paper.id], [id]: value } }))} readerNotes={paper ? nodeNotes[paper.id] ?? {} : {}} setReaderNote={(id, value) => paper && setNodeNotes((current) => ({ ...current, [paper.id]: { ...current[paper.id], [id]: value } }))} answers={paper ? nodeAnswers[paper.id] ?? {} : {}} graph={graph} analysing={analysingId === paper?.id} askingId={askingId} analyze={() => paper && void analyzePaper(paper)} askNode={askNode} saveNote={saveNote} addLink={addLink} removeLink={removeLink} openUnit={openUnit} profile={profile} />}
      {view === 'library' && <Library papers={papers} audits={audits} busyId={analysingId} analyze={analyzePaper} openUnit={openUnit} openImport={() => setImporting(true)} />}
      {view === 'graph' && <GraphView graph={graph} papers={papers} openUnit={openUnit} />}
      {view === 'discover' && <Discover papers={discoveries} saved={papers} save={saveDiscovery} refresh={refreshDiscoveries} loading={loadingDiscoveries} />}
      {view === 'notes' && <Notes notes={notes} papers={papers} openUnit={openUnit} />}
      {view === 'settings' && <Settings profile={profile} setProfile={setProfile} bridge={bridge} vaultReady={vaultReady} refresh={refreshBridge} paperCount={papers.length} />}
    </section>{importing && <ImportDialog close={() => setImporting(false)} importArxiv={importArxiv} />}
  </main>;
}

type ReaderProps = { paper?: Paper; audit?: PaperAudit; node?: AuditNode; selectedNodeId: string; setSelectedNodeId: (id: string) => void; expanded: Record<string, boolean>; setExpanded: (id: string, value: boolean) => void; readerNotes: Record<string, string>; setReaderNote: (id: string, value: string) => void; answers: Record<string, string>; graph: Graph; analysing: boolean; askingId: string | null; analyze: () => void; askNode: (node: AuditNode, question: string) => Promise<void>; saveNote: (anchor: string, nodeId: string, text: string, latex: string) => void; addLink: (link: Omit<CrossLink, 'id' | 'source' | 'createdAt'>) => Promise<void>; removeLink: (linkId: string) => Promise<void>; openUnit: (paperId: string, nodeId: string) => void; profile: Profile };

function Reader({ paper, audit, node, selectedNodeId, setSelectedNodeId, expanded, setExpanded, readerNotes, setReaderNote, answers, graph, analysing, askingId, analyze, askNode, saveNote, addLink, removeLink, openUnit, profile }: ReaderProps) {
  const [mode, setMode] = useState<ReaderMode>('source'); const [focusPath, setFocusPath] = useState(false); const [question, setQuestion] = useState('');
  useEffect(() => {
    const timer = window.setTimeout(() => setQuestion(''), 0);
    return () => window.clearTimeout(timer);
  }, [selectedNodeId]);
  if (!paper) return <EmptyVault onImport={analyze} />;
  if (!audit) return <section className="mx-auto max-w-3xl px-6 py-14"><div className="rounded-xl border border-[#d8e4d9] bg-[#f3f8f3] p-7"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#52705e]">PAPER FOLDER READY</p><h2 className="mt-2 text-2xl font-bold tracking-[-.04em]">Audit the source before reading interactively.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#627064]">Proofroom has created a stable local folder for this paper. Analyze it once to add source anchors, an outline, proof dependencies, and reusable links to your local graph.</p><div className="mt-6 flex gap-2"><button onClick={analyze} disabled={analysing} className="rounded-md bg-[#2d654f] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{analysing ? 'Auditing full paper…' : 'Analyze with local Codex'}</button><a href={`https://arxiv.org/pdf/${paper.arxivId}`} target="_blank" rel="noreferrer" className="rounded-md border border-[#cddbd0] bg-white px-4 py-2.5 text-xs font-bold text-[#39634c]">Original PDF ↗</a></div></div></section>;
  const activePath = audit.readingPaths.find((path) => path.goal.toLowerCase().includes(profile.goal.toLowerCase().split(' ')[0])) ?? audit.readingPaths[0];
  const units = focusPath && activePath ? audit.nodes.filter((item) => activePath.nodeIds.includes(item.id)) : audit.nodes;
  const page = node?.anchor.page; const pdfUrl = `https://arxiv.org/pdf/${paper.arxivId}${page ? `#page=${page}` : ''}`;
  return <section className="reader-page"><div className="reader-titlebar"><div className="min-w-0"><p className="text-[9px] font-extrabold uppercase tracking-[.12em] text-[#6d796e]">{auditLabel(audit.audit.sourceStatus)} · {audit.nodes.length} units</p><h2 className="mt-1 truncate text-base font-bold tracking-[-.02em]">{paper.title}</h2></div><div className="flex flex-wrap gap-1.5"><button onClick={() => setMode('source')} className={`reader-tab ${mode === 'source' ? 'reader-tab-active' : ''}`}>Paper</button><button onClick={() => setMode('guide')} className={`reader-tab ${mode === 'guide' ? 'reader-tab-active' : ''}`}>Guide</button><button onClick={() => setFocusPath(!focusPath)} className={`reader-tab ${focusPath ? 'reader-tab-active' : ''}`}>{focusPath ? 'All units' : 'Reading path'}</button><button onClick={analyze} disabled={analysing} className="reader-tab">{analysing ? 'Auditing…' : 'Re-audit'}</button></div></div>{activePath && focusPath && <div className="reader-path"><b>{activePath.goal}</b><span>{activePath.reason}</span></div>}
    <div className="reader-grid"><aside className="reader-outline"><div className="mb-3 flex items-center justify-between"><span className="reader-kicker">Outline</span><span className="text-[10px] text-[#7d877d]">{units.length}</span></div><div className="space-y-0.5">{units.map((item) => <button key={item.id} onClick={() => setSelectedNodeId(item.id)} className={`outline-unit ${selectedNodeId === item.id ? 'outline-unit-active' : ''}`}><span className={`outline-kind ${kindClass(item.kind)}`}>{item.kind[0].toUpperCase()}</span><span className="min-w-0"><small>{item.label}</small><b>{item.title}</b></span>{item.status !== 'verified' && <i className="ml-auto h-1.5 w-1.5 flex-none rounded-full bg-[#dfb15c]" />}</button>)}</div></aside>
      <main className="reader-document">{mode === 'source' ? <iframe title={`Original paper: ${paper.title}`} src={pdfUrl} className="reader-pdf" /> : <GuideView audit={audit} node={node} openUnit={(id) => setSelectedNodeId(id)} />}</main>
      <aside className="reader-inspector">{node ? <NodeInspector paper={paper} node={node} expanded={Boolean(expanded[node.id])} setExpanded={(value) => setExpanded(node.id, value)} readerNote={readerNotes[node.id] ?? ''} setReaderNote={(value) => setReaderNote(node.id, value)} answer={answers[node.id]} question={question} setQuestion={setQuestion} asking={askingId === node.id} ask={() => void askNode(node, question)} saveNote={saveNote} graph={graph} addLink={addLink} removeLink={removeLink} openUnit={openUnit} /> : <p className="p-4 text-xs text-[#738073]">Select a document unit.</p>}</aside></div></section>;
}

function EmptyVault({ onImport }: { onImport: () => void }) { return <section className="mx-auto max-w-3xl px-6 py-14"><div className="rounded-xl border border-dashed border-[#ccd9cd] bg-white p-9 text-center"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#617463]">LOCAL RESEARCH VAULT</p><h2 className="mt-2 text-2xl font-bold tracking-[-.04em]">Start with a paper, then let its ideas accumulate.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-[#6b756c]">Each imported paper gets its own named folder, audit, reader notes, attachments, and links into the shared dependency graph.</p><button onClick={onImport} className="mt-6 rounded-md bg-[#2d654f] px-4 py-2.5 text-xs font-bold text-white">Import an arXiv paper</button></div></section>; }

function GuideView({ audit, node, openUnit }: { audit: PaperAudit; node?: AuditNode; openUnit: (id: string) => void }) { return <article className="guide-document"><p className="reader-kicker">Paper guide</p><h3>{audit.audit.centralQuestion}</h3><p className="guide-lead">{audit.audit.mainContribution}</p><div className="guide-section"><b>Current focus</b>{node ? <button onClick={() => openUnit(node.id)} className="guide-focus">{node.label} — {node.title}</button> : <p>Select a unit from the outline.</p>}</div><div className="guide-section"><b>Audit scope</b><p>{audit.audit.sourceSummary}</p></div>{audit.audit.verificationWarnings.length > 0 && <div className="guide-warning"><b>Verification warnings</b>{audit.audit.verificationWarnings.map((item, index) => <p key={index}>• {item}</p>)}</div>}</article>;
}

type InspectorProps = { paper: Paper; node: AuditNode; expanded: boolean; setExpanded: (value: boolean) => void; readerNote: string; setReaderNote: (value: string) => void; answer?: string; question: string; setQuestion: (value: string) => void; asking: boolean; ask: () => void; saveNote: (anchor: string, nodeId: string, text: string, latex: string) => void; graph: Graph; addLink: (link: Omit<CrossLink, 'id' | 'source' | 'createdAt'>) => Promise<void>; removeLink: (linkId: string) => Promise<void>; openUnit: (paperId: string, nodeId: string) => void };

function NodeInspector({ paper, node, expanded, setExpanded, readerNote, setReaderNote, answer, question, setQuestion, asking, ask, saveNote, graph, addLink, removeLink, openUnit }: InspectorProps) {
  const [noteText, setNoteText] = useState(''); const [noteLatex, setNoteLatex] = useState(''); const [target, setTarget] = useState(''); const [relation, setRelation] = useState<CrossLink['relation']>('uses'); const [linkNote, setLinkNote] = useState('');
  const sourceId = unitId(paper.id, node.id); const candidates = graph.nodes.filter((item) => item.paperId !== paper.id); const edges = graph.edges.filter((edge) => edge.from === sourceId || edge.to === sourceId); const nodeById = new Map(graph.nodes.map((item) => [item.id, item]));
  function saveLinkedNote() { saveNote(`${node.label} · ${node.anchor.label}`, node.id, noteText, noteLatex); setNoteText(''); setNoteLatex(''); }
  function createLink() { const selected = graph.nodes.find((item) => item.id === target); if (!selected) return; void addLink({ from: { paperId: paper.id, nodeId: node.id }, to: { paperId: selected.paperId, nodeId: selected.nodeId }, relation, note: linkNote }); setTarget(''); setLinkNote(''); }
  return <div className="inspector-stack"><div><div className="flex items-start justify-between gap-2"><span className={`inline-flex rounded px-1.5 py-1 text-[9px] font-bold uppercase tracking-[.08em] ${kindClass(node.kind)}`}>{node.kind}</span><a href={`https://arxiv.org/pdf/${paper.arxivId}${node.anchor.page ? `#page=${node.anchor.page}` : ''}`} target="_blank" rel="noreferrer" className="text-[10px] font-bold text-[#35624b]">p.{node.anchor.page ?? '—'} ↗</a></div><p className="mt-3 text-[10px] text-[#788178]">{node.label} · {node.anchor.label}</p><h3 className="mt-1 text-lg font-bold leading-tight">{node.title}</h3><p className="mt-3 text-xs leading-5 text-[#536053]">{node.statement || 'No standalone statement was preserved by the audit.'}</p></div><Info label="Role" text={node.role || 'Not classified.'} /><Info label="Why it matters" text={node.whyItMatters || 'Not classified.'} />
    <section className="inspector-section"><button onClick={() => setExpanded(!expanded)} className="inspector-toggle"><span>Proof & dependencies</span><span>{expanded ? '−' : '+'}</span></button>{expanded && <div className="mt-3"><p className="mini-label">Prerequisites</p><div className="mt-1 flex flex-wrap gap-1">{node.dependencies.length ? node.dependencies.map((dependency) => <span key={dependency} className="ref-chip">{dependency}</span>) : <span className="text-[11px] text-[#758075]">No audited prerequisites.</span>}</div><p className="mini-label mt-3">Proof expansion</p>{node.proofSketch.length ? <ol className="mt-2 space-y-2">{node.proofSketch.map((step, index) => <li key={index} className="flex gap-2 text-[11px] leading-5 text-[#566256]"><span className="grid h-4 w-4 flex-none place-items-center rounded-full bg-white text-[9px] font-bold text-[#3d7057]">{index + 1}</span>{step}</li>)}</ol> : <p className="mt-2 text-[11px] leading-5 text-[#758075]">No proof sketch was certified in the audit.</p>}</div>}</section>
    <section className="inspector-section"><p className="mini-label">Ask with full-paper context</p><div className="mt-2 flex gap-1.5"><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') ask(); }} placeholder={`Ask about ${node.label}…`} className="min-w-0 flex-1 rounded border border-[#d5ddd4] px-2 py-1.5 text-[11px] outline-none" /><button onClick={ask} disabled={asking || !question.trim()} className="rounded bg-[#2d654f] px-2 text-[10px] font-bold text-white disabled:opacity-50">{asking ? '…' : 'Ask'}</button></div>{answer && <div className="mt-2 whitespace-pre-wrap rounded border border-[#dce4da] bg-white p-2.5 text-[11px] leading-5 text-[#4d5d4f]">{answer}</div>}</section>
    <section className="inspector-section"><div className="flex justify-between"><p className="mini-label">Cross-paper relations</p><span className="text-[10px] text-[#7d877d]">{edges.length}</span></div>{edges.length ? <div className="mt-2 space-y-1.5">{edges.map((edge) => { const otherId = edge.from === sourceId ? edge.to : edge.from; const other = nodeById.get(otherId); const manual = edge.source === 'manual'; const manualId = manual ? edge.id.replace('manual:', '') : ''; return <div key={edge.id} className="cross-edge"><button onClick={() => other && openUnit(other.paperId, other.nodeId)} className="min-w-0 flex-1 text-left"><b>{edge.relation}</b><span>{other ? `${other.paperTitle} · ${other.label}` : otherId}</span></button>{manual && <button onClick={() => void removeLink(manualId)} title="Remove relation" className="text-[#899189]">×</button>}</div>; })}</div> : <p className="mt-2 text-[11px] leading-5 text-[#758075]">No local cross-paper relation yet.</p>}{candidates.length > 0 && <div className="mt-3 border-t border-[#e2e7df] pt-3"><select value={target} onChange={(event) => setTarget(event.target.value)} className="w-full rounded border border-[#d5ddd4] bg-white px-2 py-1.5 text-[10px] outline-none"><option value="">Link to another audited unit…</option>{candidates.map((item) => <option key={item.id} value={item.id}>{item.paperTitle} · {item.label}</option>)}</select><div className="mt-1.5 flex gap-1.5"><select value={relation} onChange={(event) => setRelation(event.target.value as CrossLink['relation'])} className="rounded border border-[#d5ddd4] bg-white px-1.5 py-1 text-[10px]"><option value="uses">uses</option><option value="extends">extends</option><option value="background">background</option><option value="contrasts">contrasts</option></select><button onClick={createLink} disabled={!target} className="rounded border border-[#cbdacb] px-2 py-1 text-[10px] font-bold text-[#35624b] disabled:opacity-50">Add relation</button></div><input value={linkNote} onChange={(event) => setLinkNote(event.target.value)} placeholder="Optional rationale" className="mt-1.5 w-full rounded border border-[#d5ddd4] px-2 py-1.5 text-[10px] outline-none" /></div>}</section>
    <section className="inspector-section"><p className="mini-label">Your reader layer</p><textarea value={readerNote} onChange={(event) => setReaderNote(event.target.value)} placeholder="Interpretation, caveat, or alternate proof route…" className="mt-2 block min-h-16 w-full rounded border border-[#d5ddd4] p-2 text-[11px] leading-5 outline-none" /></section>
    <section className="inspector-section"><p className="mini-label">Linked LaTeX note</p><textarea value={noteText} onChange={(event) => setNoteText(event.target.value)} placeholder="Capture a derivation or question…" className="mt-2 block min-h-14 w-full rounded border border-[#d5ddd4] p-2 text-[11px] leading-5 outline-none" /><input value={noteLatex} onChange={(event) => setNoteLatex(event.target.value)} placeholder="LaTeX, e.g. \\|u\\|_{H^1} \\le C" className="mt-1.5 block w-full rounded border border-[#d5ddd4] px-2 py-1.5 text-[10px] outline-none" />{noteLatex && <div className="mt-2 rounded bg-[#f4f6f2] p-1.5"><Latex value={noteLatex} small /></div>}<button onClick={saveLinkedNote} disabled={!noteText.trim()} className="mt-2 rounded bg-[#2d654f] px-2.5 py-1.5 text-[10px] font-bold text-white disabled:opacity-50">Save note</button></section>
  </div>;
}

function Info({ label, text }: { label: string; text: string }) { return <div className="rounded border border-[#e2e7df] bg-[#fbfcfa] p-2.5"><p className="mini-label">{label}</p><p className="mt-1 text-[11px] leading-5 text-[#586458]">{text}</p></div>; }

function Library({ papers, audits, busyId, analyze, openUnit, openImport }: { papers: Paper[]; audits: Record<string, PaperAudit>; busyId: string | null; analyze: (paper: Paper) => Promise<void>; openUnit: (paperId: string, nodeId: string) => void; openImport: () => void }) { return <div className="mx-auto max-w-5xl p-6 sm:p-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="reader-kicker">Local paper vault</p><h2 className="mt-1 text-3xl font-bold tracking-[-.055em]">A reusable research library</h2><p className="mt-2 text-sm text-[#707970]">Each paper has a stable folder with its audit, reader state, attachments, exports, and cross-paper links.</p></div><button onClick={openImport} className="rounded-md bg-[#2d654f] px-3 py-2 text-xs font-bold text-white">+ Import paper</button></div><div className="mt-8 grid gap-3 sm:grid-cols-2">{papers.map((paper) => <article key={paper.id} className="rounded-xl border border-[#e1e6df] bg-white p-4"><div className="flex justify-between gap-2"><span className="rounded bg-[#edf4ee] px-2 py-1 text-[10px] font-bold text-[#46705a]">{paper.category}</span><span className={`rounded px-2 py-1 text-[10px] font-bold ${audits[paper.id] ? 'bg-[#e1f1e5] text-[#2d654f]' : 'bg-[#f4f1ea] text-[#856640]'}`}>{audits[paper.id] ? `${audits[paper.id].nodes.length} units` : 'Not audited'}</span></div><h3 className="mt-4 text-base font-bold leading-5">{paper.title}</h3><p className="mt-2 text-xs text-[#697169]">{paper.authors} · arXiv:{paper.arxivId}</p><p className="mt-2 truncate font-mono text-[10px] text-[#8a9389]">{paper.folder ?? 'Creating folder…'}</p><div className="mt-4 flex items-center justify-between"><button onClick={() => openUnit(paper.id, audits[paper.id]?.nodes[0]?.id ?? '')} className="text-xs font-bold text-[#2d654f]">Open reader →</button><button onClick={() => void analyze(paper)} disabled={busyId === paper.id} className="rounded border border-[#d2ded3] px-2.5 py-1.5 text-[10px] font-bold text-[#426652] disabled:opacity-50">{busyId === paper.id ? 'Auditing…' : audits[paper.id] ? 'Re-audit' : 'Analyze'}</button></div></article>)}</div></div>; }

function GraphView({ graph, papers, openUnit }: { graph: Graph; papers: Paper[]; openUnit: (paperId: string, nodeId: string) => void }) { const nodeById = new Map(graph.nodes.map((item) => [item.id, item])); const cross = graph.edges.filter((edge) => nodeById.get(edge.from)?.paperId !== nodeById.get(edge.to)?.paperId); return <div className="mx-auto max-w-6xl p-6 sm:p-10"><div><p className="reader-kicker">Local dependency graph</p><h2 className="mt-1 text-3xl font-bold tracking-[-.055em]">Results that travel between papers</h2><p className="mt-2 text-sm text-[#707970]">Audited units are nodes. Arrows are proof dependencies or explicit relations you add while reading.</p></div>{graph.nodes.length === 0 ? <div className="mt-8 rounded-xl border border-dashed border-[#d8dfd7] p-8 text-sm text-[#7a837a]">Audit at least one paper to build its local graph.</div> : <><div className="graph-canvas mt-8">{papers.filter((paper) => graph.nodes.some((node) => node.paperId === paper.id)).map((paper) => <section key={paper.id} className="graph-paper"><div className="flex items-center justify-between"><b>{paper.title}</b><span>{graph.nodes.filter((node) => node.paperId === paper.id).length} units</span></div><div className="mt-3 flex flex-wrap gap-2">{graph.nodes.filter((node) => node.paperId === paper.id).map((node) => <button key={node.id} onClick={() => openUnit(node.paperId, node.nodeId)} className={`graph-node ${kindClass(node.kind)}`}>{node.label}</button>)}</div></section>)}</div><section className="mt-7 rounded-xl border border-[#e0e6df] bg-white p-4"><div className="flex justify-between"><div><p className="reader-kicker">Cross-paper arrows</p><h3 className="mt-1 text-lg font-bold">{cross.length} relation{cross.length === 1 ? '' : 's'}</h3></div><span className="text-[10px] text-[#7c857c]">Add relations from a unit inspector</span></div><div className="mt-4 space-y-2">{cross.length ? cross.map((edge) => { const from = nodeById.get(edge.from); const to = nodeById.get(edge.to); return <div key={edge.id} className="graph-edge"><button onClick={() => from && openUnit(from.paperId, from.nodeId)}>{from ? `${from.paperTitle} · ${from.label}` : edge.from}</button><span>— {edge.relation} →</span><button onClick={() => to && openUnit(to.paperId, to.nodeId)}>{to ? `${to.paperTitle} · ${to.label}` : edge.to}</button>{edge.note && <small>{edge.note}</small>}</div>; }) : <p className="text-sm text-[#788178]">No cross-paper arrows yet. Link a theorem, definition, or external result from the right-hand reader inspector.</p>}</div></section></>}</div>; }

function Discover({ papers, saved, save, refresh, loading }: { papers: Paper[]; saved: Paper[]; save: (paper: Paper) => Promise<void>; refresh: () => Promise<void>; loading: boolean }) { return <div className="mx-auto max-w-5xl p-6 sm:p-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="reader-kicker">Daily discovery</p><h2 className="mt-1 text-3xl font-bold tracking-[-.055em]">Relevant papers today</h2><p className="mt-2 text-sm text-[#707970]">A lightweight arXiv feed for your selected mathematical area.</p></div><button onClick={() => void refresh()} className="rounded-md border border-[#d8e0d7] bg-white px-3 py-2 text-xs font-bold text-[#436150]">{loading ? 'Refreshing…' : 'Refresh arXiv'}</button></div><div className="mt-8 space-y-3">{papers.map((paper) => { const inVault = saved.some((item) => item.arxivId === paper.arxivId); return <article key={paper.arxivId} className="rounded-xl border border-[#e1e6df] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="max-w-2xl"><span className="rounded bg-[#edf4ee] px-2 py-1 text-[10px] font-bold text-[#46705a]">{paper.category}</span><h3 className="mt-3 text-lg font-bold">{paper.title}</h3><p className="mt-1 text-xs text-[#737c73]">{paper.authors} · arXiv:{paper.arxivId}</p><p className="mt-3 text-sm leading-6 text-[#606a60]">{paper.abstract}</p></div><button disabled={inVault} onClick={() => void save(paper)} className={`rounded-md px-3 py-2 text-xs font-bold ${inVault ? 'bg-[#edf0ec] text-[#869086]' : 'bg-[#2d654f] text-white'}`}>{inVault ? 'In vault' : '+ Save paper'}</button></div></article>; })}</div></div>; }

function Notes({ notes, papers, openUnit }: { notes: Note[]; papers: Paper[]; openUnit: (paperId: string, nodeId: string) => void }) { return <div className="mx-auto max-w-4xl p-6 sm:p-10"><p className="reader-kicker">Knowledge you keep</p><h2 className="mt-1 text-3xl font-bold tracking-[-.055em]">Linked notes</h2><p className="mt-2 text-sm text-[#707970]">Notes live with their paper, not in an unstructured notebook.</p><div className="mt-8 space-y-3">{notes.length ? notes.map((note) => { const paper = papers.find((item) => item.id === note.paperId); return <article key={note.id} className="rounded-xl border border-[#e1e6df] bg-white p-5"><div className="flex justify-between gap-3"><div><b className="text-sm">{note.anchor}</b><p className="mt-2 text-sm leading-6 text-[#596359]">{note.text}</p>{note.latex && <div className="mt-3 rounded bg-[#f4f6f2] p-2"><Latex value={note.latex} small /></div>}</div><button onClick={() => openUnit(note.paperId, note.nodeId)} className="shrink-0 text-xs font-bold text-[#2d654f]">{paper?.title ?? 'Open paper'} →</button></div></article>; }) : <div className="rounded-xl border border-dashed border-[#d8dfd7] p-8 text-center text-sm text-[#7a837a]">No notes yet. Select a theorem, definition, or proof unit to add one.</div>}</div></div>; }

function Settings({ profile, setProfile, bridge, vaultReady, refresh, paperCount }: { profile: Profile; setProfile: (value: Profile | ((old: Profile) => Profile)) => void; bridge: Bridge | null; vaultReady: boolean; refresh: () => Promise<void>; paperCount: number }) { const update = (key: keyof Profile, value: string) => setProfile((current) => ({ ...current, [key]: value })); const model = bridge?.models.find((item) => item.id === profile.model); const efforts = model?.efforts.length ? model.efforts : ['low', 'medium', 'high']; return <div className="mx-auto max-w-3xl p-6 sm:p-10"><p className="reader-kicker">Preferences</p><h2 className="mt-1 text-3xl font-bold tracking-[-.055em]">Reader & local Codex</h2><p className="mt-2 text-sm text-[#707970]">Your background steers audits; model and effort are sent only to your local Codex app-server.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><Select label="Background" value={profile.level} options={['Undergraduate', 'Graduate student', 'Researcher']} onChange={(value) => update('level', value)} /><Select label="Primary area" value={profile.area} options={['math.AG', 'math.AP', 'math.DG', 'math.PR', 'math.OC']} onChange={(value) => update('area', value)} /><Select label="Reading goal" value={profile.goal} options={['Survey new work', 'Understand proofs', 'Apply a result', 'Reproduce a proof']} onChange={(value) => update('goal', value)} /><Select label="Codex model" value={profile.model} options={(bridge?.models ?? []).map((item) => item.id)} labels={(bridge?.models ?? []).reduce<Record<string, string>>((result, item) => ({ ...result, [item.id]: item.label }), {})} onChange={(value) => update('model', value)} emptyLabel="Codex default" /><Select label="Reasoning effort" value={profile.reasoning} options={efforts} onChange={(value) => update('reasoning', value)} /></div><div className={`mt-5 rounded-xl border p-4 text-xs leading-5 ${bridge?.account ? 'border-[#dce7dd] bg-[#eff6f0] text-[#52705e]' : 'border-[#f0ddc7] bg-[#fff8ed] text-[#825b2d]'}`}><div className="flex justify-between gap-3"><b>Local vault & Codex bridge</b><button onClick={() => void refresh()} className="rounded border border-current/20 bg-white/60 px-2 py-1 text-[10px] font-bold">Refresh</button></div><p className="mt-1">{bridge?.account ? `Connected with local ${bridge.account.type}${bridge.account.planType ? ` (${bridge.account.planType})` : ''}.` : 'Bridge not connected.'} {vaultReady ? `${paperCount} paper folder${paperCount === 1 ? '' : 's'} in the local vault.` : 'Opening local vault…'} No API key is used.</p></div></div>; }

function Select({ label, value, options, labels = {}, onChange, emptyLabel }: { label: string; value: string; options: string[]; labels?: Record<string, string>; onChange: (value: string) => void; emptyLabel?: string }) { return <label className="rounded-xl border border-[#e1e6df] bg-white p-4"><span className="text-xs font-bold">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="mt-3 block w-full rounded-md border border-[#dce3da] bg-[#fbfcf9] px-2.5 py-2 text-xs text-[#415c4b] outline-none"><option value="">{emptyLabel ?? 'Codex default'}</option>{options.map((option) => <option key={option} value={option}>{labels[option] ?? option}</option>)}</select></label>; }

function ImportDialog({ close, importArxiv }: { close: () => void; importArxiv: (value: string) => Promise<void> }) { const [value, setValue] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent) { event.preventDefault(); if (!value.trim()) return; setBusy(true); setError(''); try { await importArxiv(value); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The paper could not be imported.'); } finally { setBusy(false); } } return <div className="fixed inset-0 z-30 grid place-items-center bg-[#18261e]/35 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="reader-kicker">ArXiv to paper vault</p><h2 className="mt-1 text-xl font-bold">Import & audit a paper</h2></div><button type="button" onClick={close} className="text-lg text-[#788078]">×</button></div><p className="mt-3 text-xs leading-5 text-[#737c73]">Paste an arXiv ID, abstract URL, or PDF URL. Proofroom creates a stable local folder, then asks your local Codex subscription to audit the primary source.</p><label className="mt-5 block"><span className="text-xs font-bold">arXiv ID or URL</span><input autoFocus value={value} onChange={(event) => setValue(event.target.value)} placeholder="e.g. 2608.04121 or https://arxiv.org/abs/2608.04121" className="mt-1.5 block w-full rounded-md border border-[#dce3da] px-3 py-2.5 text-xs outline-none" /></label>{error && <p className="mt-3 rounded-md bg-[#fff1ed] p-2.5 text-xs text-[#a34c3a]">{error}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-md px-3 py-2 text-xs text-[#697369]">Cancel</button><button disabled={busy} className="rounded-md bg-[#2d654f] px-3 py-2 text-xs font-bold text-white disabled:opacity-60">{busy ? 'Importing & auditing…' : 'Import & analyze'}</button></div></form></div>; }
