'use client';

import katex from 'katex';
import { FormEvent, useEffect, useMemo, useState } from 'react';

type View = 'reader' | 'library' | 'graph' | 'discover' | 'notes' | 'settings';
type ReaderMode = 'source' | 'interactive';
type EditionMode = 'original' | 'working';
type Paper = { id: string; title: string; authors: string; category: string; arxivId: string; abstract: string; state: 'To read' | 'Reading' | 'Read'; tags: string[]; folder?: string };
type Profile = { level: string; area: string; goal: string; model: string; reasoning: string };
type Note = { id: string; paperId: string; nodeId: string; anchor: string; text: string; latex: string; createdAt: string };
type Anchor = { label: string; page: number | null; confidence: 'verified' | 'approximate' | 'unverified' };
type NodeKind = 'definition' | 'assumption' | 'notation' | 'lemma' | 'proposition' | 'theorem' | 'corollary' | 'proof' | 'equation' | 'remark' | 'example' | 'section' | 'external-result';
type AuditNode = { id: string; kind: NodeKind; label: string; title: string; statement: string; status: 'verified' | 'needs-verification' | 'unavailable'; anchor: Anchor; role: string; dependencies: string[]; proofSketch: string[]; whyItMatters: string; expandable: boolean };
type WorkingPatch = { id: string; kind: 'replace' | 'delete' | 'add'; nodeId: string; title: string; statement: string; nodeKind: NodeKind | ''; afterNodeId: string; rationale: string; dependencies: string[]; proofSketch: string[]; source: 'manual' | 'ai'; createdAt: string };
type EditorialSuggestion = { hasIssue: boolean; replacement: string; rationale: string; confidence: 'high' | 'medium' | 'low' };
type VersionChange = { label: string; changeType: 'added' | 'removed' | 'strengthened' | 'weakened' | 'corrected' | 'reorganized' | 'wording'; before: string; after: string; significance: 'mathematical' | 'proof-level' | 'expository' | 'uncertain'; dependencyImpact: string };
type VersionComparison = { summary: string; changedUnits: VersionChange[]; proofChanges: string[]; notationChanges: string[]; editorialChanges: string[]; dependencyImpact: string[]; readingRecommendation: string; warnings: string[] };
type CrossLink = { id: string; from: { paperId: string; nodeId: string }; to: { paperId: string; nodeId: string }; relation: 'uses' | 'extends' | 'background' | 'contrasts'; note: string; source: 'manual' | 'audit'; createdAt?: string };
type AuditCrossLink = { fromNodeId: string; targetPaperId: string; targetNodeId: string; relation: CrossLink['relation']; rationale: string };
type PaperAudit = { threadId: string; generatedAt: string; rawText: string; audit: { sourceStatus: 'full-text-read' | 'partial-text-read' | 'blocked'; sourceSummary: string; centralQuestion: string; mainContribution: string; verificationWarnings: string[] }; nodes: AuditNode[]; readingPaths: { goal: string; nodeIds: string[]; reason: string }[]; crossPaperLinks: AuditCrossLink[]; openQuestions: string[] };
type GraphNode = { id: string; paperId: string; paperTitle: string; arxivId: string; nodeId: string; label: string; title: string; kind: NodeKind; page: number | null; status: AuditNode['status'] };
type GraphEdge = { id: string; from: string; to: string; relation: CrossLink['relation']; source: 'manual' | 'audit'; note?: string };
type Graph = { version: number; updatedAt: string | null; nodes: GraphNode[]; edges: GraphEdge[] };
type Bridge = { running: boolean; account: { type: string; planType: string | null } | null; models: { id: string; label: string; efforts: string[]; defaultEffort: string | null; isDefault: boolean }[]; lastError: string | null };
type VaultSnapshot = { papers: Paper[]; audits: Record<string, PaperAudit>; notes: Note[]; nodeNotes: Record<string, Record<string, string>>; nodeAnswers: Record<string, Record<string, string>>; expanded: Record<string, Record<string, boolean>>; patches: Record<string, WorkingPatch[]>; profile: Profile | null; links: CrossLink[]; graph: Graph; vault: { paperFolders: { paperId: string; folder: string }[] } };

const bridgeUrl = 'http://127.0.0.1:4318';
const preferenceKey = 'proofroom-reader-preferences-v1';
const defaultProfile: Profile = { level: 'Graduate student', area: 'math.AP', goal: 'Understand proofs', model: '', reasoning: 'medium' };
const emptyGraph: Graph = { version: 1, updatedAt: null, nodes: [], edges: [] };
const fallbackDiscoveries: Paper[] = [
  { id: 'd-1', title: 'Stability estimates for degenerate elliptic equations', authors: 'E. Moreno', category: 'math.AP', arxivId: '2608.05192', abstract: 'New stability estimates that extend compactness methods to a degenerate setting.', state: 'To read', tags: ['elliptic PDE', 'stability'] },
  { id: 'd-2', title: 'Geodesic convexity in spaces of probability measures', authors: 'N. Berg · K. Ito', category: 'math.OC', arxivId: '2608.05014', abstract: 'A concise treatment of geodesic convexity and its variational consequences.', state: 'To read', tags: ['optimal transport', 'convexity'] },
];

function Latex({ value, small = false }: { value: string; small?: boolean }) {
  const html = useMemo(() => katex.renderToString(value || '\\text{Add a LaTeX formula}', { throwOnError: false, strict: 'ignore', displayMode: true }), [value]);
  return <div className={`${small ? 'text-sm' : 'text-base'} overflow-x-auto text-[#284235]`} dangerouslySetInnerHTML={{ __html: html }} />;
}

function readString(value: unknown, fallback = '') { return typeof value === 'string' ? value : fallback; }
function asArray(value: unknown) { return Array.isArray(value) ? value : []; }
function parseAudit(rawText: string, threadId: string): PaperAudit {
  const clean = rawText.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
  const first = clean.indexOf('{'); const last = clean.lastIndexOf('}');
  if (first < 0 || last <= first) throw new Error('Codex returned no structured audit. Try again.');
  const data = JSON.parse(clean.slice(first, last + 1)) as Record<string, unknown>;
  const auditData = data.audit as Record<string, unknown> | undefined;
  if (!auditData || !Array.isArray(data.nodes)) throw new Error('Codex returned an incomplete audit. Try again.');
  const kinds = new Set<NodeKind>(['definition', 'assumption', 'notation', 'lemma', 'proposition', 'theorem', 'corollary', 'proof', 'equation', 'remark', 'example', 'section', 'external-result']);
  const statuses = new Set<AuditNode['status']>(['verified', 'needs-verification', 'unavailable']);
  const sourceStatus = new Set<PaperAudit['audit']['sourceStatus']>(['full-text-read', 'partial-text-read', 'blocked']);
  const confidence = new Set<Anchor['confidence']>(['verified', 'approximate', 'unverified']);
  return {
    threadId,
    generatedAt: new Date().toISOString(),
    rawText,
    audit: {
      sourceStatus: sourceStatus.has(auditData.sourceStatus as PaperAudit['audit']['sourceStatus']) ? auditData.sourceStatus as PaperAudit['audit']['sourceStatus'] : 'partial-text-read',
      sourceSummary: readString(auditData.sourceSummary, 'No source summary returned.'),
      centralQuestion: readString(auditData.centralQuestion, 'Not established.'),
      mainContribution: readString(auditData.mainContribution, 'Not established.'),
      verificationWarnings: asArray(auditData.verificationWarnings).map(String),
    },
    nodes: data.nodes.map((item, index): AuditNode => {
      const entry = item as Record<string, unknown>; const anchor = entry.anchor as Record<string, unknown> | undefined;
      return { id: readString(entry.id, `unit-${index + 1}`), kind: kinds.has(entry.kind as NodeKind) ? entry.kind as NodeKind : 'section', label: readString(entry.label, `Unit ${index + 1}`), title: readString(entry.title, readString(entry.label, `Unit ${index + 1}`)), statement: readString(entry.statement), status: statuses.has(entry.status as AuditNode['status']) ? entry.status as AuditNode['status'] : 'needs-verification', anchor: { label: readString(anchor?.label, 'Source location unavailable'), page: typeof anchor?.page === 'number' ? anchor.page : null, confidence: confidence.has(anchor?.confidence as Anchor['confidence']) ? anchor?.confidence as Anchor['confidence'] : 'unverified' }, role: readString(entry.role), dependencies: asArray(entry.dependencies).map(String), proofSketch: asArray(entry.proofSketch).map(String), whyItMatters: readString(entry.whyItMatters), expandable: Boolean(entry.expandable) };
    }),
    readingPaths: asArray(data.readingPaths).map((item) => { const path = item as Record<string, unknown>; return { goal: readString(path.goal, 'Reading path'), nodeIds: asArray(path.nodeIds).map(String), reason: readString(path.reason) }; }),
    crossPaperLinks: asArray(data.crossPaperLinks).map((item) => { const link = item as Record<string, unknown>; const relation = ['uses', 'extends', 'background', 'contrasts'].includes(readString(link.relation)) ? readString(link.relation) as CrossLink['relation'] : 'uses'; return { fromNodeId: readString(link.fromNodeId), targetPaperId: readString(link.targetPaperId), targetNodeId: readString(link.targetNodeId), relation, rationale: readString(link.rationale) }; }).filter((link) => link.fromNodeId && link.targetPaperId && link.targetNodeId),
    openQuestions: asArray(data.openQuestions).map(String),
  };
}

function kindClass(kind: NodeKind) { if (kind === 'theorem' || kind === 'corollary') return 'bg-[#295e49] text-white'; if (kind === 'lemma' || kind === 'proposition') return 'bg-[#dceee1] text-[#286448]'; if (kind === 'definition' || kind === 'notation' || kind === 'assumption') return 'bg-[#e5edf7] text-[#3c6390]'; return 'bg-[#f4eee7] text-[#816552]'; }
function auditLabel(status: PaperAudit['audit']['sourceStatus']) { return status === 'full-text-read' ? 'Full text audited' : status === 'partial-text-read' ? 'Partial source audit' : 'Source access blocked'; }
function unitId(paperId: string, nodeId: string) { return `${paperId}::${nodeId}`; }
function makeId() { return typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : `patch-${Date.now()}-${Math.random().toString(36).slice(2)}`; }
function parseJsonObject(rawText: string) {
  const clean = rawText.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '');
  const first = clean.indexOf('{'); const last = clean.lastIndexOf('}');
  if (first < 0 || last <= first) throw new Error('Codex returned no structured suggestion.');
  return JSON.parse(clean.slice(first, last + 1)) as Record<string, unknown>;
}
function patchForNode(patches: WorkingPatch[], nodeId: string) {
  if (nodeId.startsWith('working-')) return patches.find((patch) => patch.kind === 'add' && `working-${patch.id}` === nodeId);
  return patches.findLast((patch) => patch.kind === 'replace' && patch.nodeId === nodeId);
}
function applyWorkingPatches(nodes: AuditNode[], patches: WorkingPatch[]) {
  const deleted = new Set(patches.filter((patch) => patch.kind === 'delete').map((patch) => patch.nodeId));
  const replacements = new Map(patches.filter((patch) => patch.kind === 'replace').map((patch) => [patch.nodeId, patch]));
  const result: AuditNode[] = [];
  for (const node of nodes) {
    if (!deleted.has(node.id)) {
      const replacement = replacements.get(node.id);
      result.push(replacement ? { ...node, kind: replacement.nodeKind || node.kind, title: replacement.title || node.title, statement: replacement.statement || node.statement, dependencies: replacement.dependencies.length ? replacement.dependencies : node.dependencies, proofSketch: replacement.proofSketch.length ? replacement.proofSketch : node.proofSketch, status: 'needs-verification', anchor: { ...node.anchor, confidence: 'approximate' } } : node);
    }
    for (const patch of patches.filter((item) => item.kind === 'add' && item.afterNodeId === node.id)) {
      result.push({ id: `working-${patch.id}`, kind: patch.nodeKind || 'proposition', label: 'Working edition', title: patch.title, statement: patch.statement, status: 'needs-verification', anchor: { label: 'Working edition — reader addition', page: null, confidence: 'unverified' }, role: patch.rationale || 'Reader-added proposition', dependencies: patch.dependencies, proofSketch: patch.proofSketch, whyItMatters: 'This unit was added in the working edition and is not part of the original source.', expandable: true });
    }
  }
  return result;
}

export default function Home() {
  const [view, setView] = useState<View>('reader');
  const [papers, setPapers] = useState<Paper[]>([]);
  const [audits, setAudits] = useState<Record<string, PaperAudit>>({});
  const [notes, setNotes] = useState<Note[]>([]);
  const [nodeNotes, setNodeNotes] = useState<Record<string, Record<string, string>>>({});
  const [nodeAnswers, setNodeAnswers] = useState<Record<string, Record<string, string>>>({});
  const [expanded, setExpanded] = useState<Record<string, Record<string, boolean>>>({});
  const [patches, setPatches] = useState<Record<string, WorkingPatch[]>>({});
  const [, setLinks] = useState<CrossLink[]>([]);
  const [graph, setGraph] = useState<Graph>(emptyGraph);
  const [profile, setProfile] = useState<Profile>(defaultProfile);
  const [discoveries, setDiscoveries] = useState<Paper[]>(fallbackDiscoveries);
  const [selectedPaperId, setSelectedPaperId] = useState('');
  const [selectedNodeId, setSelectedNodeId] = useState('');
  const [importing, setImporting] = useState(false);
  const [analysingId, setAnalysingId] = useState<string | null>(null);
  const [askingId, setAskingId] = useState<string | null>(null);
  const [bridge, setBridge] = useState<Bridge | null>(null);
  const [vaultReady, setVaultReady] = useState(false);
  const [loadingDiscoveries, setLoadingDiscoveries] = useState(false);
  const [notice, setNotice] = useState('');

  const paper = papers.find((item) => item.id === selectedPaperId) ?? papers[0];
  const audit = paper ? audits[paper.id] : undefined;

  function notify(message: string) { setNotice(message); window.setTimeout(() => setNotice(''), 4500); }
  function applySnapshot(snapshot: VaultSnapshot) {
    setPapers(snapshot.papers); setAudits(snapshot.audits); setNotes(snapshot.notes); setNodeNotes(snapshot.nodeNotes); setNodeAnswers(snapshot.nodeAnswers); setExpanded(snapshot.expanded); setPatches(snapshot.patches ?? {}); setLinks(snapshot.links); setGraph(snapshot.graph ?? emptyGraph);
    if (snapshot.profile) setProfile({ ...defaultProfile, ...snapshot.profile });
    setSelectedPaperId((current) => snapshot.papers.some((item) => item.id === current) ? current : snapshot.papers[0]?.id ?? '');
  }
  async function refreshBridge() { try { const response = await fetch(`${bridgeUrl}/status`); const data = await response.json() as Bridge; setBridge(data); if (data.models?.length) setProfile((current) => data.models.some((item) => item.id === current.model) ? current : { ...current, model: data.models.find((item) => item.isDefault)?.id ?? '' }); } catch { setBridge(null); } }
  async function loadVault() { try { const response = await fetch(`${bridgeUrl}/vault`); if (!response.ok) throw new Error(); applySnapshot(await response.json() as VaultSnapshot); } catch { const saved = localStorage.getItem(preferenceKey); if (saved) { try { setProfile({ ...defaultProfile, ...JSON.parse(saved) }); } catch {} } } finally { setVaultReady(true); } }
  useEffect(() => {
    const timer = window.setTimeout(() => { void loadVault(); void refreshBridge(); }, 0);
    return () => window.clearTimeout(timer);
    // The bridge functions intentionally run once when this local reader mounts.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  useEffect(() => { localStorage.setItem(preferenceKey, JSON.stringify(profile)); if (vaultReady) void fetch(`${bridgeUrl}/vault/profile`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ profile }) }); }, [profile, vaultReady]);
  useEffect(() => {
    if (!vaultReady || !paper) return;
    const timer = window.setTimeout(() => { void fetch(`${bridgeUrl}/vault/reader`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paperId: paper.id, reader: { notes: notes.filter((item) => item.paperId === paper.id), nodeNotes: nodeNotes[paper.id] ?? {}, nodeAnswers: nodeAnswers[paper.id] ?? {}, expanded: expanded[paper.id] ?? {} } }) }); }, 500);
    return () => window.clearTimeout(timer);
  }, [vaultReady, paper, notes, nodeNotes, nodeAnswers, expanded]);

  async function savePaper(incoming: Paper) {
    const response = await fetch(`${bridgeUrl}/vault/paper`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper: incoming }) });
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not create the paper folder.');
    const stored = data.paper as Paper;
    setPapers((current) => [stored, ...current.filter((item) => item.id !== stored.id && item.arxivId !== stored.arxivId)]);
    return stored;
  }
  async function updatePaperInfo(incoming: Paper) {
    const response = await fetch(`${bridgeUrl}/vault/paper/update`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper: incoming }) });
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not update the paper record.');
    const stored = data.paper as Paper; setPapers((current) => current.map((item) => item.id === stored.id ? stored : item)); notify('Paper record updated.');
  }
  async function removePaperFromVault(paperId: string) {
    const response = await fetch(`${bridgeUrl}/vault/paper/delete`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paperId }) });
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not remove the paper.');
    applySnapshot(data.snapshot as VaultSnapshot); notify('Paper removed from the library and archived locally for recovery.');
  }
  async function analyzePaper(target: Paper) {
    setAnalysingId(target.id);
    try {
      const response = await fetch(`${bridgeUrl}/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper: target, profile }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Local Codex analysis failed.');
      const stored = data.paper as Paper; const next = parseAudit(readString(data.text), readString(data.threadId));
      const saved = await fetch(`${bridgeUrl}/vault/audit`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper: stored, audit: next }) });
      const snapshot = await saved.json(); if (!saved.ok) throw new Error(snapshot.error || 'Could not save the local audit.');
      const sourceLabel = data.primarySource?.kind === 'tex' ? 'TeX-first source' : 'PDF fallback';
      setPapers((current) => [snapshot.paper as Paper, ...current.filter((item) => item.id !== stored.id && item.arxivId !== stored.arxivId)]); setAudits((current) => ({ ...current, [stored.id]: next })); setGraph(snapshot.graph ?? emptyGraph); setLinks(snapshot.links ?? []); setSelectedPaperId(stored.id); setSelectedNodeId(next.nodes[0]?.id ?? ''); setView('reader'); notify(`${next.nodes.length} audited document units are ready · ${sourceLabel}.`); void refreshBridge();
    } catch (error) { notify(`${error instanceof Error ? error.message : 'Analysis failed.'} Start the local bridge and try again.`); void refreshBridge(); }
    finally { setAnalysingId(null); }
  }
  async function importArxiv(raw: string) {
    const response = await fetch(`/api/arxiv?id=${encodeURIComponent(raw)}`); const data = await response.json();
    if (!response.ok || !data.papers?.[0]) throw new Error('Paper not found on arXiv.');
    const incoming = { ...data.papers[0], state: 'Reading' } as Paper; const existing = papers.find((item) => item.arxivId === incoming.arxivId); setImporting(false); await analyzePaper(existing ?? incoming);
  }
  async function saveDiscovery(candidate: Paper) { try { const stored = await savePaper({ ...candidate, state: 'To read' }); setSelectedPaperId(stored.id); notify('Paper saved with its own local folder.'); } catch (error) { notify(error instanceof Error ? error.message : 'Could not save the paper.'); } }
  async function askNode(targetNode: AuditNode, question: string) { if (!audit?.threadId || !paper || !question.trim()) return; setAskingId(targetNode.id); try { const response = await fetch(`${bridgeUrl}/node-question`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper, profile, node: targetNode, question, threadId: audit.threadId }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Codex did not answer this unit.'); setNodeAnswers((current) => ({ ...current, [paper.id]: { ...current[paper.id], [targetNode.id]: readString(data.text) } })); } catch (error) { notify(error instanceof Error ? error.message : 'The local Codex question failed.'); } finally { setAskingId(null); } }
  function saveNote(anchor: string, nodeId: string, text: string, latex: string) { if (!paper || !text.trim()) return; setNotes((current) => [{ id: `n-${Date.now()}`, paperId: paper.id, nodeId, anchor, text, latex, createdAt: 'just now' }, ...current]); notify('Linked note saved in this paper folder.'); }
  async function addLink(link: Omit<CrossLink, 'id' | 'source' | 'createdAt'>) { try { const response = await fetch(`${bridgeUrl}/vault/link`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ link }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not create the relation.'); setLinks((current) => current.some((item) => item.id === data.link.id) ? current : [...current, data.link]); setGraph(data.graph ?? emptyGraph); notify('Cross-paper relation added to the local graph.'); } catch (error) { notify(error instanceof Error ? error.message : 'Could not create the relation.'); } }
  async function removeLink(linkId: string) { const response = await fetch(`${bridgeUrl}/vault/link/delete`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ linkId }) }); const data = await response.json(); if (response.ok) { setLinks((current) => current.filter((item) => item.id !== linkId)); setGraph(data.graph ?? emptyGraph); } }
  async function saveWorkingPatches(paperId: string, nextPatches: WorkingPatch[]) {
    const response = await fetch(`${bridgeUrl}/vault/patches`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paperId, patches: nextPatches }) });
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not save the working edition.');
    setPatches((current) => ({ ...current, [paperId]: data.patches as WorkingPatch[] })); setGraph(data.graph ?? emptyGraph); notify('Working edition saved locally.');
  }
  async function suggestEditorialFix(targetNode: AuditNode) {
    if (!audit?.threadId || !paper) throw new Error('Run the full-paper audit first.');
    const response = await fetch(`${bridgeUrl}/node-edit/suggest`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper, profile, node: targetNode, threadId: audit.threadId }) });
    const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Codex could not inspect this unit.');
    const parsed = parseJsonObject(readString(data.text));
    return { hasIssue: Boolean(parsed.hasIssue), replacement: readString(parsed.replacement), rationale: readString(parsed.rationale), confidence: ['high', 'medium', 'low'].includes(readString(parsed.confidence)) ? readString(parsed.confidence) as EditorialSuggestion['confidence'] : 'low' };
  }
  async function refreshDiscoveries() { setLoadingDiscoveries(true); try { const response = await fetch(`/api/arxiv?category=${encodeURIComponent(profile.area)}`); const data = await response.json(); if (!response.ok || !data.papers?.length) throw new Error(); setDiscoveries(data.papers); } catch { notify('arXiv is unavailable right now; showing local examples.'); } finally { setLoadingDiscoveries(false); } }
  function openUnit(paperId: string, nodeId: string) { setSelectedPaperId(paperId); setSelectedNodeId(nodeId); setView('reader'); }

  return <main className="min-h-screen bg-[#f8f8f5] text-[#20251f] lg:grid lg:grid-cols-[54px_235px_minmax(0,1fr)]">
    <nav className="hidden min-h-screen flex-col items-center gap-2 border-r border-[#e0e4dd] bg-[#273b31] py-4 text-[#dfece4] lg:flex"><div className="mb-4 grid h-8 w-8 place-items-center rounded-lg bg-[#5b806d] text-[10px] font-black">PR</div>{([['reader', '⌁', 'Read'], ['library', '▦', 'Library'], ['graph', '⌘', 'Graph'], ['discover', '✦', 'Discover'], ['notes', '✎', 'Notes'], ['settings', '⚙', 'Settings']] as const).map(([target, icon, label]) => <button key={target} onClick={() => setView(target)} title={label} className={`grid h-9 w-9 place-items-center rounded-lg text-base ${view === target ? 'bg-[#476956] text-white' : 'hover:bg-[#3b5b49]'}`}>{icon}</button>)}<div className="flex-1" /><span title={bridge?.account ? 'Local Codex ready' : 'Local Codex unavailable'} className={`mb-2 h-2 w-2 rounded-full ${bridge?.account ? 'bg-[#75ca94]' : 'bg-[#d9b159]'}`} /></nav>
    <aside className="hidden min-h-screen flex-col border-r border-[#e2e6e0] bg-[#f0f2ed] p-4 lg:flex"><div className="flex items-start justify-between"><div><p className="text-[9px] font-extrabold uppercase tracking-[.13em] text-[#778078]">LOCAL VAULT</p><h1 className="mt-1 text-lg font-bold tracking-[-.04em]">Papers</h1></div><button onClick={() => setImporting(true)} className="grid h-7 w-7 place-items-center rounded-md border border-[#ccd5cc] text-lg text-[#426652]">+</button></div><button onClick={() => setImporting(true)} className="my-4 rounded-md bg-[#deebe1] px-3 py-2 text-left text-[11px] font-bold text-[#2d604b]">+ Import & audit arXiv paper</button><div className="mb-2 flex justify-between text-[10px] font-bold text-[#677068]"><span>YOUR LIBRARY</span><span>{papers.length}</span></div><div className="min-h-0 flex-1 space-y-1 overflow-y-auto">{papers.length ? papers.map((item) => <button key={item.id} onClick={() => { setSelectedPaperId(item.id); setView('reader'); }} className={`w-full rounded-lg p-2 text-left ${item.id === paper?.id && view === 'reader' ? 'bg-[#dfe9e0]' : 'hover:bg-[#e7ebe6]'}`}><span className="flex items-start gap-2"><i className={`mt-1 h-1.5 w-1.5 flex-none rounded-full ${audits[item.id] ? 'bg-[#499b70]' : 'bg-[#d6b756]'}`} /><span><b className="block text-[11px] leading-[1.35]">{item.title}</b><small className="mt-1 block text-[9px] text-[#788178]">{item.arxivId}</small>{item.folder && <small className="mt-1 block truncate font-mono text-[8px] text-[#8b948a]">{item.folder}</small>}</span></span></button>) : <p className="rounded-lg border border-dashed border-[#d5ddd5] p-3 text-[11px] leading-5 text-[#788178]">Your vault is empty. Import an arXiv paper to create its first folder.</p>}</div><button onClick={() => { setView('discover'); void refreshDiscoveries(); }} className="mt-3 flex items-center gap-2 border-t border-[#dce2db] pt-3 text-left"><span className="grid h-6 w-6 place-items-center rounded bg-[#e3eee6] text-[#327055]">◌</span><span><b className="block text-[10px]">Discover</b><small className="text-[9px] text-[#788078]">New arXiv papers</small></span></button></aside>
    <section className="min-w-0"><header className="flex h-12 items-center justify-between border-b border-[#e2e6e0] bg-white px-4 sm:px-6"><div className="min-w-0 truncate text-[11px] text-[#727b72]">{view === 'reader' && paper ? <><span className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-[#4a9b70]" />{paper.title}</> : view === 'graph' ? 'Local dependency graph' : view[0].toUpperCase() + view.slice(1)}</div><div className="flex items-center gap-2"><div className="hidden gap-1 sm:flex">{(['reader', 'library', 'graph', 'notes'] as View[]).map((item) => <button key={item} onClick={() => setView(item)} className={`rounded px-1.5 py-1 text-[10px] ${view === item ? 'font-bold text-[#285f49]' : 'text-[#7a837a]'}`}>{item}</button>)}</div><button onClick={() => setImporting(true)} className="rounded-md border border-[#d8e0d7] bg-white px-2.5 py-1.5 text-[10px] text-[#486552]">+ Import</button></div></header>{notice && <div className="border-b border-[#ecd9bb] bg-[#fff8ed] px-5 py-2 text-xs text-[#76552e]">{notice}</div>}
      {view === 'reader' && <Reader paper={paper} audit={audit} selectedNodeId={selectedNodeId} setSelectedNodeId={setSelectedNodeId} expanded={paper ? expanded[paper.id] ?? {} : {}} setExpanded={(id, value) => paper && setExpanded((current) => ({ ...current, [paper.id]: { ...current[paper.id], [id]: value } }))} readerNotes={paper ? nodeNotes[paper.id] ?? {} : {}} setReaderNote={(id, value) => paper && setNodeNotes((current) => ({ ...current, [paper.id]: { ...current[paper.id], [id]: value } }))} answers={paper ? nodeAnswers[paper.id] ?? {} : {}} patches={paper ? patches[paper.id] ?? [] : []} savePatches={(next) => paper ? saveWorkingPatches(paper.id, next) : Promise.resolve()} suggestEdit={suggestEditorialFix} graph={graph} analysing={analysingId === paper?.id} askingId={askingId} analyze={() => paper && void analyzePaper(paper)} askNode={askNode} saveNote={saveNote} addLink={addLink} removeLink={removeLink} openUnit={openUnit} profile={profile} />}
      {view === 'library' && <Library papers={papers} audits={audits} patches={patches} busyId={analysingId} analyze={analyzePaper} updatePaper={updatePaperInfo} removePaper={removePaperFromVault} openUnit={openUnit} openImport={() => setImporting(true)} />}
      {view === 'graph' && <GraphView graph={graph} papers={papers} openUnit={openUnit} />}
      {view === 'discover' && <Discover papers={discoveries} saved={papers} save={saveDiscovery} refresh={refreshDiscoveries} loading={loadingDiscoveries} />}
      {view === 'notes' && <Notes notes={notes} papers={papers} openUnit={openUnit} />}
      {view === 'settings' && <Settings profile={profile} setProfile={setProfile} bridge={bridge} vaultReady={vaultReady} refresh={refreshBridge} paperCount={papers.length} />}
    </section>{importing && <ImportDialog close={() => setImporting(false)} importArxiv={importArxiv} />}
  </main>;
}

type ReaderProps = { paper?: Paper; audit?: PaperAudit; selectedNodeId: string; setSelectedNodeId: (id: string) => void; expanded: Record<string, boolean>; setExpanded: (id: string, value: boolean) => void; readerNotes: Record<string, string>; setReaderNote: (id: string, value: string) => void; answers: Record<string, string>; patches: WorkingPatch[]; savePatches: (patches: WorkingPatch[]) => Promise<void>; suggestEdit: (node: AuditNode) => Promise<EditorialSuggestion>; graph: Graph; analysing: boolean; askingId: string | null; analyze: () => void; askNode: (node: AuditNode, question: string) => Promise<void>; saveNote: (anchor: string, nodeId: string, text: string, latex: string) => void; addLink: (link: Omit<CrossLink, 'id' | 'source' | 'createdAt'>) => Promise<void>; removeLink: (linkId: string) => Promise<void>; openUnit: (paperId: string, nodeId: string) => void; profile: Profile };

function Reader({ paper, audit, selectedNodeId, setSelectedNodeId, expanded, setExpanded, readerNotes, setReaderNote, answers, patches, savePatches, suggestEdit, graph, analysing, askingId, analyze, askNode, saveNote, addLink, removeLink, openUnit, profile }: ReaderProps) {
  const [mode, setMode] = useState<ReaderMode>('interactive'); const [edition, setEdition] = useState<EditionMode>('working'); const [focusPath, setFocusPath] = useState(false); const [question, setQuestion] = useState(''); const [changesOpen, setChangesOpen] = useState(false); const [comparisonOpen, setComparisonOpen] = useState(false);
  const originalNodes = useMemo(() => audit?.nodes ?? [], [audit]);
  const editionNodes = useMemo(() => edition === 'working' ? applyWorkingPatches(originalNodes, patches) : originalNodes, [edition, originalNodes, patches]);
  const node = editionNodes.find((item) => item.id === selectedNodeId) ?? editionNodes[0];
  useEffect(() => {
    const timer = window.setTimeout(() => setQuestion(''), 0);
    return () => window.clearTimeout(timer);
  }, [selectedNodeId]);
  useEffect(() => {
    if (!audit || editionNodes.some((item) => item.id === selectedNodeId)) return;
    const timer = window.setTimeout(() => setSelectedNodeId(editionNodes[0]?.id ?? ''), 0);
    return () => window.clearTimeout(timer);
  }, [audit, editionNodes, selectedNodeId, setSelectedNodeId]);
  if (!paper) return <EmptyVault onImport={analyze} />;
  if (!audit) return <section className="mx-auto max-w-3xl px-6 py-14"><div className="rounded-xl border border-[#d8e4d9] bg-[#f3f8f3] p-7"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#52705e]">PAPER FOLDER READY</p><h2 className="mt-2 text-2xl font-bold tracking-[-.04em]">Audit the source before reading interactively.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#627064]">Proofroom has created a stable local folder for this paper. Analyze it once to add source anchors, an outline, proof dependencies, and reusable links to your local graph.</p><div className="mt-6 flex gap-2"><button onClick={analyze} disabled={analysing} className="rounded-md bg-[#2d654f] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{analysing ? 'Auditing full paper…' : 'Analyze with local Codex'}</button><a href={`https://arxiv.org/pdf/${paper.arxivId}`} target="_blank" rel="noreferrer" className="rounded-md border border-[#cddbd0] bg-white px-4 py-2.5 text-xs font-bold text-[#39634c]">Original PDF ↗</a></div></div></section>;
  const activePath = audit.readingPaths.find((path) => path.goal.toLowerCase().includes(profile.goal.toLowerCase().split(' ')[0])) ?? audit.readingPaths[0];
  const units = focusPath && activePath ? editionNodes.filter((item) => activePath.nodeIds.includes(item.id)) : editionNodes;
  const page = node?.anchor.page; const pdfUrl = `https://arxiv.org/pdf/${paper.arxivId}${page ? `#page=${page}` : ''}`;
  return <section className="reader-page"><div className="reader-titlebar"><div className="min-w-0"><p className="text-[9px] font-extrabold uppercase tracking-[.12em] text-[#6d796e]">{auditLabel(audit.audit.sourceStatus)} · {editionNodes.length} visible units</p><h2 className="mt-1 truncate text-base font-bold tracking-[-.02em]">{paper.title}</h2></div><div className="flex flex-wrap gap-1.5"><button onClick={() => setMode('source')} className={`reader-tab ${mode === 'source' ? 'reader-tab-active' : ''}`}>Original PDF</button><button onClick={() => setMode('interactive')} className={`reader-tab ${mode === 'interactive' ? 'reader-tab-active' : ''}`}>Interactive paper</button><span className="reader-tab-divider" /><button onClick={() => setEdition('original')} className={`reader-tab ${edition === 'original' ? 'reader-tab-active' : ''}`}>Original</button><button onClick={() => { setEdition('working'); setMode('interactive'); }} className={`reader-tab ${edition === 'working' ? 'reader-tab-active' : ''}`}>Working edition</button><button onClick={() => setChangesOpen(true)} className="reader-tab">Changes {patches.length}</button><button onClick={() => setComparisonOpen(true)} className="reader-tab">Compare versions</button><button onClick={() => setFocusPath(!focusPath)} className={`reader-tab ${focusPath ? 'reader-tab-active' : ''}`}>{focusPath ? 'All units' : 'Focus path'}</button><button onClick={analyze} disabled={analysing} className="reader-tab">{analysing ? 'Auditing…' : 'Re-audit'}</button></div></div>{activePath && focusPath && <div className="reader-path"><b>{activePath.goal}</b><span>{activePath.reason}</span></div>}
    <div className="reader-grid"><aside className="reader-outline"><div className="mb-3 flex items-center justify-between"><span className="reader-kicker">Logical outline</span><span className="text-[10px] text-[#7d877d]">{units.length}</span></div><div className="space-y-0.5">{units.map((item) => { const changed = patchForNode(patches, item.id); return <button key={item.id} onClick={() => setSelectedNodeId(item.id)} className={`outline-unit ${selectedNodeId === item.id ? 'outline-unit-active' : ''}`}><span className={`outline-kind ${kindClass(item.kind)}`}>{item.kind[0].toUpperCase()}</span><span className="min-w-0"><small>{item.label}</small><b>{item.title}</b></span>{changed && <i className="working-dot" title={changed.kind === 'add' ? 'Added in working edition' : 'Edited in working edition'}>W</i>}{item.status !== 'verified' && !changed && <i className="ml-auto h-1.5 w-1.5 flex-none rounded-full bg-[#dfb15c]" />}</button>; })}</div></aside>
      <main className="reader-document">{mode === 'source' ? <iframe title={`Original paper: ${paper.title}`} src={pdfUrl} className="reader-pdf" /> : <InteractiveDocument audit={audit} nodes={units} selectedNodeId={node?.id ?? ''} setSelectedNodeId={setSelectedNodeId} expanded={expanded} setExpanded={setExpanded} edition={edition} patches={patches} />}</main>
      <aside className="reader-inspector">{node ? <NodeInspector key={`${edition}:${node.id}`} paper={paper} node={node} originalNode={audit.nodes.find((item) => item.id === node.id)} edition={edition} patches={patches} savePatches={savePatches} suggestEdit={suggestEdit} expanded={Boolean(expanded[node.id])} setExpanded={(value) => setExpanded(node.id, value)} readerNote={readerNotes[node.id] ?? ''} setReaderNote={(value) => setReaderNote(node.id, value)} answer={answers[node.id]} question={question} setQuestion={setQuestion} asking={askingId === node.id} ask={() => void askNode(node, question)} saveNote={saveNote} graph={graph} addLink={addLink} removeLink={removeLink} openUnit={openUnit} /> : <p className="p-4 text-xs text-[#738073]">Select a document unit.</p>}</aside></div>{changesOpen && <EditionPanel audit={audit} patches={patches} savePatches={savePatches} close={() => setChangesOpen(false)} />}{comparisonOpen && <VersionComparisonPanel paper={paper} profile={profile} audit={audit} openUnit={openUnit} close={() => setComparisonOpen(false)} />}</section>;
}

function EmptyVault({ onImport }: { onImport: () => void }) { return <section className="mx-auto max-w-3xl px-6 py-14"><div className="rounded-xl border border-dashed border-[#ccd9cd] bg-white p-9 text-center"><p className="text-[10px] font-extrabold uppercase tracking-[.12em] text-[#617463]">LOCAL RESEARCH VAULT</p><h2 className="mt-2 text-2xl font-bold tracking-[-.04em]">Start with a paper, then let its ideas accumulate.</h2><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-[#6b756c]">Each imported paper gets its own named folder, audit, reader notes, attachments, and links into the shared dependency graph.</p><button onClick={onImport} className="mt-6 rounded-md bg-[#2d654f] px-4 py-2.5 text-xs font-bold text-white">Import an arXiv paper</button></div></section>; }

function InteractiveDocument({ audit, nodes, selectedNodeId, setSelectedNodeId, expanded, setExpanded, edition, patches }: { audit: PaperAudit; nodes: AuditNode[]; selectedNodeId: string; setSelectedNodeId: (id: string) => void; expanded: Record<string, boolean>; setExpanded: (id: string, value: boolean) => void; edition: EditionMode; patches: WorkingPatch[] }) {
  const selected = nodes.find((node) => node.id === selectedNodeId) ?? nodes[0];
  return <article className="interactive-document"><header className="interactive-lead"><div className="flex items-center justify-between gap-3"><p className="reader-kicker">{edition === 'working' ? 'Working edition' : 'Audited original'}</p><span className="edition-status">{edition === 'working' ? `${patches.length} reversible change${patches.length === 1 ? '' : 's'}` : 'Immutable source layer'}</span></div><h3>{audit.audit.centralQuestion}</h3><p>{audit.audit.mainContribution}</p></header>
    {selected && <DependencyNeighborhood node={selected} nodes={nodes} open={setSelectedNodeId} />}
    <div className="interactive-units">{nodes.map((node) => { const isOpen = Boolean(expanded[node.id]); const patch = patchForNode(patches, node.id); return <section key={node.id} onClick={() => setSelectedNodeId(node.id)} className={`paper-unit ${selectedNodeId === node.id ? 'paper-unit-selected' : ''} ${patch ? 'paper-unit-working' : ''}`}><div className="paper-unit-heading"><span className={`outline-kind ${kindClass(node.kind)}`}>{node.kind[0].toUpperCase()}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="paper-unit-label">{node.label}</span>{patch && <span className="working-badge">{patch.kind === 'add' ? 'Reader addition' : patch.source === 'ai' ? 'AI-assisted edit' : 'Reader edit'}</span>}<span className="source-badge">{node.anchor.page ? `p. ${node.anchor.page}` : node.anchor.confidence}</span></div><h4>{node.title}</h4></div></div><p className="paper-unit-statement">{node.statement || 'No standalone statement was extracted for this unit.'}</p><div className="paper-unit-actions"><button onClick={(event) => { event.stopPropagation(); setExpanded(node.id, !isOpen); }}>{isOpen ? 'Hide details' : 'Expand proof & dependencies'}</button><span>{node.dependencies.length} prerequisite{node.dependencies.length === 1 ? '' : 's'}</span></div>{isOpen && <div className="paper-unit-details"><div><b>Prerequisites</b><div className="dependency-links">{node.dependencies.length ? node.dependencies.map((dependency) => { const target = nodes.find((item) => item.id === dependency); return <button key={dependency} onClick={(event) => { event.stopPropagation(); if (target) setSelectedNodeId(target.id); }}>{target ? `${target.label} · ${target.title}` : dependency}</button>; }) : <span>No audited prerequisites.</span>}</div></div><div><b>Proof route</b>{node.proofSketch.length ? <ol>{node.proofSketch.map((step, index) => <li key={index}><span>{index + 1}</span>{step}</li>)}</ol> : <p>No proof expansion was certified in the full-paper audit.</p>}</div></div>}</section>; })}</div>
  </article>;
}

function DependencyNeighborhood({ node, nodes, open }: { node: AuditNode; nodes: AuditNode[]; open: (id: string) => void }) {
  const prerequisites = node.dependencies.map((id) => nodes.find((item) => item.id === id)).filter(Boolean) as AuditNode[];
  const dependents = nodes.filter((item) => item.dependencies.includes(node.id));
  return <section className="dependency-neighborhood"><div className="dependency-column"><span>Prerequisites</span>{prerequisites.length ? prerequisites.map((item) => <button key={item.id} onClick={() => open(item.id)}><small>{item.kind}</small><b>{item.label}</b><em>{item.title}</em></button>) : <p>No local prerequisites</p>}</div><div className="dependency-arrow">→</div><button onClick={() => open(node.id)} className="dependency-current"><small>{node.kind}</small><b>{node.label}</b><span>{node.title}</span></button><div className="dependency-arrow">→</div><div className="dependency-column"><span>Used by</span>{dependents.length ? dependents.map((item) => <button key={item.id} onClick={() => open(item.id)}><small>{item.kind}</small><b>{item.label}</b><em>{item.title}</em></button>) : <p>No audited dependents</p>}</div></section>;
}

function EditionPanel({ audit, patches, savePatches, close }: { audit: PaperAudit; patches: WorkingPatch[]; savePatches: (patches: WorkingPatch[]) => Promise<void>; close: () => void }) {
  const [busyId, setBusyId] = useState('');
  async function remove(patchId: string) { setBusyId(patchId); try { await savePatches(patches.filter((patch) => patch.id !== patchId)); } finally { setBusyId(''); } }
  return <div className="edition-overlay" onMouseDown={(event) => { if (event.currentTarget === event.target) close(); }}><section className="edition-panel"><header><div><p className="reader-kicker">Reversible source layer</p><h3>Working edition changes</h3></div><button onClick={close}>×</button></header><p className="edition-explainer">The arXiv PDF and audit stay immutable. Every correction, hidden unit, and reader-added proposition is stored separately and can be reverted here.</p>{patches.length ? <div className="edition-list">{patches.map((patch) => { const original = audit.nodes.find((node) => node.id === patch.nodeId); return <article key={patch.id}><div><span className="working-badge">{patch.kind}</span><small>{patch.source === 'ai' ? 'AI-assisted' : 'Manual'} · {original?.label ?? 'Reader addition'}</small></div><b>{patch.title || original?.title || 'Hidden source unit'}</b><p>{patch.rationale || (patch.kind === 'delete' ? 'Hidden from the working edition.' : 'No rationale recorded.')}</p><button disabled={busyId === patch.id} onClick={() => void remove(patch.id)}>{busyId === patch.id ? 'Reverting…' : patch.kind === 'delete' ? 'Restore unit' : 'Revert change'}</button></article>; })}</div> : <div className="edition-empty">No changes yet. Select a theorem, lemma, definition, or proof unit to edit the working edition.</div>}<footer><button onClick={close}>Done</button>{patches.length > 0 && <button className="edition-revert-all" onClick={() => void savePatches([])}>Revert all changes</button>}</footer></section></div>;
}

function VersionComparisonPanel({ paper, profile, audit, openUnit, close }: { paper: Paper; profile: Profile; audit: PaperAudit; openUnit: (paperId: string, nodeId: string) => void; close: () => void }) {
  const baseId = paper.arxivId.replace(/v\d+$/i, '');
  const [fromVersion, setFromVersion] = useState(`${baseId}v1`); const [toVersion, setToVersion] = useState(paper.arxivId.match(/v\d+$/i) ? paper.arxivId : baseId); const [result, setResult] = useState<VersionComparison | null>(null); const [sources, setSources] = useState<{ from: string; to: string } | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function compare() {
    if (!fromVersion.trim() || !toVersion.trim()) return;
    setBusy(true); setError(''); setResult(null);
    try {
      const response = await fetch(`${bridgeUrl}/compare-versions`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ paper, profile, fromVersion, toVersion }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Version comparison failed.');
      const parsed = parseJsonObject(readString(data.text));
      setResult({ summary: readString(parsed.summary), changedUnits: asArray(parsed.changedUnits) as VersionChange[], proofChanges: asArray(parsed.proofChanges).map(String), notationChanges: asArray(parsed.notationChanges).map(String), editorialChanges: asArray(parsed.editorialChanges).map(String), dependencyImpact: asArray(parsed.dependencyImpact).map(String), readingRecommendation: readString(parsed.readingRecommendation), warnings: asArray(parsed.warnings).map(String) });
      setSources(data.sources ?? null);
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'Version comparison failed.'); } finally { setBusy(false); }
  }
  function matchingNode(change: VersionChange) { const needle = change.label.toLowerCase(); return audit.nodes.find((node) => node.label.toLowerCase() === needle || node.title.toLowerCase().includes(needle) || needle.includes(node.label.toLowerCase())); }
  return <div className="edition-overlay" onMouseDown={(event) => { if (event.currentTarget === event.target && !busy) close(); }}><section className="version-panel"><header><div><p className="reader-kicker">AI mathematical diff</p><h3>Compare arXiv versions</h3><span>TeX-first · local Codex · no API key</span></div><button onClick={close} disabled={busy}>×</button></header><div className="version-picker"><label><span>Version A</span><input value={fromVersion} onChange={(event) => setFromVersion(event.target.value)} placeholder={`${baseId}v1`} /></label><span>→</span><label><span>Version B</span><input value={toVersion} onChange={(event) => setToVersion(event.target.value)} placeholder={baseId} /></label><button onClick={() => void compare()} disabled={busy || !fromVersion.trim() || !toVersion.trim()}>{busy ? 'Reading both sources…' : 'Compare with AI'}</button></div>{error && <p className="version-error">{error}</p>}{busy && <div className="version-loading"><b>Auditing both complete versions</b><p>Proofroom is fetching TeX first, resolving theorem structure, and tracing changes through the dependency graph. This can take several minutes.</p></div>}
    {result && <div className="version-results"><section className="version-summary"><div className="flex items-center justify-between gap-3"><p className="reader-kicker">Executive difference</p>{sources && <span>{sources.from.toUpperCase()} → {sources.to.toUpperCase()}</span>}</div><h4>{result.summary}</h4><p>{result.readingRecommendation}</p></section><section><div className="version-section-head"><b>Changed mathematical units</b><span>{result.changedUnits.length}</span></div><div className="version-changes">{result.changedUnits.map((change, index) => { const match = matchingNode(change); return <article key={`${change.label}-${index}`}><div><span className={`version-change-type version-${change.changeType}`}>{change.changeType}</span><span>{change.significance}</span>{match && <button onClick={() => { openUnit(paper.id, match.id); close(); }}>Open {match.label}</button>}</div><h5>{change.label}</h5><div className="version-before-after"><div><b>Before</b><p>{change.before || 'Not present.'}</p></div><div><b>After</b><p>{change.after || 'Removed.'}</p></div></div><footer><b>Dependency impact</b><p>{change.dependencyImpact || 'No verified dependency impact.'}</p></footer></article>; })}</div></section><div className="version-detail-grid"><ComparisonList title="Proof changes" items={result.proofChanges} /><ComparisonList title="Dependency changes" items={result.dependencyImpact} /><ComparisonList title="Notation changes" items={result.notationChanges} /><ComparisonList title="Editorial changes" items={result.editorialChanges} /></div>{result.warnings.length > 0 && <ComparisonList title="Verification warnings" items={result.warnings} warning />}</div>}
  </section></div>;
}

function ComparisonList({ title, items, warning = false }: { title: string; items: string[]; warning?: boolean }) { return <section className={`comparison-list ${warning ? 'comparison-warning' : ''}`}><div><b>{title}</b><span>{items.length}</span></div>{items.length ? <ul>{items.map((item, index) => <li key={index}>{item}</li>)}</ul> : <p>No material change identified.</p>}</section>; }

function WorkingEditionEditor({ node, originalNode, edition, patches, savePatches, suggestEdit }: { node: AuditNode; originalNode?: AuditNode; edition: EditionMode; patches: WorkingPatch[]; savePatches: (patches: WorkingPatch[]) => Promise<void>; suggestEdit: (node: AuditNode) => Promise<EditorialSuggestion> }) {
  const currentPatch = patchForNode(patches, node.id);
  const [mode, setMode] = useState<'idle' | 'edit' | 'add'>('idle');
  const [title, setTitle] = useState(node.title);
  const [statement, setStatement] = useState(node.statement);
  const [nodeKind, setNodeKind] = useState<NodeKind>(node.kind);
  const [dependencies, setDependencies] = useState(node.dependencies.join('\n'));
  const [proofSketch, setProofSketch] = useState(node.proofSketch.join('\n'));
  const [rationale, setRationale] = useState(currentPatch?.rationale ?? '');
  const [suggestion, setSuggestion] = useState<EditorialSuggestion | null>(null);
  const [busy, setBusy] = useState('');
  const nodeKinds: NodeKind[] = ['definition', 'assumption', 'notation', 'lemma', 'proposition', 'theorem', 'corollary', 'proof', 'equation', 'remark', 'example', 'section', 'external-result'];
  const lines = (value: string) => value.split(/[\n,]+/).map((item) => item.trim()).filter(Boolean);
  function beginEdit() { setMode('edit'); setTitle(node.title); setStatement(node.statement); setNodeKind(node.kind); setDependencies(node.dependencies.join('\n')); setProofSketch(node.proofSketch.join('\n')); setRationale(currentPatch?.rationale ?? ''); }
  function beginAdd() { setMode('add'); setTitle(''); setStatement(''); setNodeKind('proposition'); setDependencies(node.id); setProofSketch(''); setRationale('Reader-added result.'); }
  async function saveEditor() {
    if (!title.trim() || !statement.trim()) return;
    setBusy('save');
    const timestamp = new Date().toISOString();
    const shared = { title: title.trim(), statement: statement.trim(), nodeKind, rationale: rationale.trim(), dependencies: lines(dependencies), proofSketch: lines(proofSketch), source: 'manual' as const, createdAt: timestamp };
    try {
      if (mode === 'add') {
        const anchor = currentPatch?.kind === 'add' ? currentPatch.afterNodeId : originalNode?.id ?? node.id;
        const addition: WorkingPatch = { id: makeId(), kind: 'add', nodeId: '', afterNodeId: anchor, ...shared };
        await savePatches([...patches, addition]);
      } else if (currentPatch?.kind === 'add') {
        await savePatches(patches.map((patch) => patch.id === currentPatch.id ? { ...patch, ...shared } : patch));
      } else {
        const replacement: WorkingPatch = { id: currentPatch?.id ?? makeId(), kind: 'replace', nodeId: originalNode?.id ?? node.id, afterNodeId: '', ...shared };
        await savePatches([...patches.filter((patch) => !(patch.kind === 'replace' && patch.nodeId === replacement.nodeId)), replacement]);
      }
      setMode('idle');
    } finally { setBusy(''); }
  }
  async function hideUnit() {
    setBusy('hide');
    try {
      if (currentPatch?.kind === 'add') await savePatches(patches.filter((patch) => patch.id !== currentPatch.id));
      else {
        const sourceId = originalNode?.id ?? node.id;
        const hidden: WorkingPatch = { id: makeId(), kind: 'delete', nodeId: sourceId, title: node.title, statement: '', nodeKind: '', afterNodeId: '', rationale: 'Hidden from the working edition.', dependencies: [], proofSketch: [], source: 'manual', createdAt: new Date().toISOString() };
        await savePatches([...patches.filter((patch) => !(patch.nodeId === sourceId && (patch.kind === 'replace' || patch.kind === 'delete'))), hidden]);
      }
    } finally { setBusy(''); }
  }
  async function revertUnit() {
    setBusy('revert');
    try {
      if (currentPatch?.kind === 'add') await savePatches(patches.filter((patch) => patch.id !== currentPatch.id));
      else { const sourceId = originalNode?.id ?? node.id; await savePatches(patches.filter((patch) => patch.nodeId !== sourceId || (patch.kind !== 'replace' && patch.kind !== 'delete'))); }
    } finally { setBusy(''); }
  }
  async function inspectSource() {
    if (!originalNode) return;
    setBusy('ai'); setSuggestion(null);
    try { setSuggestion(await suggestEdit(originalNode)); } finally { setBusy(''); }
  }
  async function applySuggestion() {
    if (!originalNode || !suggestion?.hasIssue || !suggestion.replacement.trim()) return;
    setBusy('apply');
    const replacement: WorkingPatch = { id: currentPatch?.kind === 'replace' ? currentPatch.id : makeId(), kind: 'replace', nodeId: originalNode.id, title: node.title, statement: suggestion.replacement.trim(), nodeKind: node.kind, afterNodeId: '', rationale: suggestion.rationale, dependencies: node.dependencies, proofSketch: node.proofSketch, source: 'ai', createdAt: new Date().toISOString() };
    try { await savePatches([...patches.filter((patch) => !(patch.kind === 'replace' && patch.nodeId === originalNode.id)), replacement]); setSuggestion(null); } finally { setBusy(''); }
  }
  return <section className="inspector-section working-editor"><div className="working-editor-head"><div><p className="mini-label">Working edition</p><span>{edition === 'original' ? 'Edits are saved to the separate working layer.' : currentPatch ? 'This unit differs from the source.' : 'Original source is untouched.'}</span></div>{currentPatch && <span className="working-badge">{currentPatch.source === 'ai' ? 'AI edit' : currentPatch.kind}</span>}</div>
    <div className="working-editor-actions"><button onClick={beginEdit}>Edit unit</button><button onClick={beginAdd}>Add after</button><button onClick={() => void inspectSource()} disabled={!originalNode || Boolean(busy)}>{busy === 'ai' ? 'Proofreading…' : 'AI proofread'}</button><button onClick={() => void hideUnit()} disabled={Boolean(busy)}>{currentPatch?.kind === 'add' ? 'Remove addition' : 'Hide unit'}</button>{currentPatch && <button onClick={() => void revertUnit()} disabled={Boolean(busy)}>Revert</button>}</div>
    {mode !== 'idle' && <div className="working-editor-form"><label><span>Unit type</span><select value={nodeKind} onChange={(event) => setNodeKind(event.target.value as NodeKind)}>{nodeKinds.map((kind) => <option key={kind} value={kind}>{kind}</option>)}</select></label><label><span>Title</span><input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label><span>Statement (LaTeX allowed)</span><textarea value={statement} onChange={(event) => setStatement(event.target.value)} /></label><label><span>Dependencies — node IDs, one per line</span><textarea value={dependencies} onChange={(event) => setDependencies(event.target.value)} /></label><label><span>Proof route — one step per line</span><textarea value={proofSketch} onChange={(event) => setProofSketch(event.target.value)} /></label><label><span>Editorial rationale</span><input value={rationale} onChange={(event) => setRationale(event.target.value)} /></label><div><button className="working-editor-save" onClick={() => void saveEditor()} disabled={busy === 'save' || !title.trim() || !statement.trim()}>{busy === 'save' ? 'Saving…' : mode === 'add' ? 'Add to working edition' : 'Save working edit'}</button><button onClick={() => setMode('idle')}>Cancel</button></div></div>}
    {suggestion && <div className={`editorial-suggestion ${suggestion.hasIssue ? '' : 'editorial-clear'}`}><div><b>{suggestion.hasIssue ? 'Possible source issue' : 'No source issue found'}</b><span>{suggestion.confidence} confidence</span></div><p>{suggestion.rationale}</p>{suggestion.hasIssue && <><blockquote>{suggestion.replacement}</blockquote><button onClick={() => void applySuggestion()} disabled={busy === 'apply'}>{busy === 'apply' ? 'Applying…' : 'Apply AI correction'}</button></>}</div>}
  </section>;
}

type InspectorProps = { paper: Paper; node: AuditNode; originalNode?: AuditNode; edition: EditionMode; patches: WorkingPatch[]; savePatches: (patches: WorkingPatch[]) => Promise<void>; suggestEdit: (node: AuditNode) => Promise<EditorialSuggestion>; expanded: boolean; setExpanded: (value: boolean) => void; readerNote: string; setReaderNote: (value: string) => void; answer?: string; question: string; setQuestion: (value: string) => void; asking: boolean; ask: () => void; saveNote: (anchor: string, nodeId: string, text: string, latex: string) => void; graph: Graph; addLink: (link: Omit<CrossLink, 'id' | 'source' | 'createdAt'>) => Promise<void>; removeLink: (linkId: string) => Promise<void>; openUnit: (paperId: string, nodeId: string) => void };

function NodeInspector({ paper, node, originalNode, edition, patches, savePatches, suggestEdit, expanded, setExpanded, readerNote, setReaderNote, answer, question, setQuestion, asking, ask, saveNote, graph, addLink, removeLink, openUnit }: InspectorProps) {
  const [noteText, setNoteText] = useState(''); const [noteLatex, setNoteLatex] = useState(''); const [target, setTarget] = useState(''); const [relation, setRelation] = useState<CrossLink['relation']>('uses'); const [linkNote, setLinkNote] = useState('');
  const sourceId = unitId(paper.id, node.id); const candidates = graph.nodes.filter((item) => item.paperId !== paper.id); const edges = graph.edges.filter((edge) => edge.from === sourceId || edge.to === sourceId); const nodeById = new Map(graph.nodes.map((item) => [item.id, item]));
  const prerequisiteNodes = edges.filter((edge) => edge.from === sourceId && edge.relation === 'uses').map((edge) => nodeById.get(edge.to)).filter(Boolean) as GraphNode[];
  const dependentNodes = edges.filter((edge) => edge.to === sourceId && edge.relation === 'uses').map((edge) => nodeById.get(edge.from)).filter(Boolean) as GraphNode[];
  function saveLinkedNote() { saveNote(`${node.label} · ${node.anchor.label}`, node.id, noteText, noteLatex); setNoteText(''); setNoteLatex(''); }
  function createLink() { const selected = graph.nodes.find((item) => item.id === target); if (!selected) return; void addLink({ from: { paperId: paper.id, nodeId: node.id }, to: { paperId: selected.paperId, nodeId: selected.nodeId }, relation, note: linkNote }); setTarget(''); setLinkNote(''); }
  return <div className="inspector-stack"><WorkingEditionEditor node={node} originalNode={originalNode} edition={edition} patches={patches} savePatches={savePatches} suggestEdit={suggestEdit} /><div><div className="flex items-start justify-between gap-2"><span className={`inline-flex rounded px-1.5 py-1 text-[9px] font-bold uppercase tracking-[.08em] ${kindClass(node.kind)}`}>{node.kind}</span><a href={`https://arxiv.org/pdf/${paper.arxivId}${node.anchor.page ? `#page=${node.anchor.page}` : ''}`} target="_blank" rel="noreferrer" className="text-[10px] font-bold text-[#35624b]">p.{node.anchor.page ?? '—'} ↗</a></div><p className="mt-3 text-[10px] text-[#788178]">{node.label} · {node.anchor.label}</p><h3 className="mt-1 text-lg font-bold leading-tight">{node.title}</h3><p className="mt-3 text-xs leading-5 text-[#536053]">{node.statement || 'No standalone statement was preserved by the audit.'}</p></div><Info label="Role" text={node.role || 'Not classified.'} /><Info label="Why it matters" text={node.whyItMatters || 'Not classified.'} />
    <section className="inspector-section logical-neighborhood"><div className="flex items-center justify-between"><p className="mini-label">Logical neighborhood</p><span>{prerequisiteNodes.length} in · {dependentNodes.length} out</span></div><div className="logical-flow"><div><b>Depends on</b>{prerequisiteNodes.length ? prerequisiteNodes.map((item) => <button key={item.id} onClick={() => openUnit(item.paperId, item.nodeId)}><small>{item.kind}</small><span>{item.label} · {item.title}</span></button>) : <p>No audited prerequisites.</p>}</div><i>→</i><div className="logical-current"><small>{node.kind}</small><b>{node.label}</b></div><i>→</i><div><b>Used by</b>{dependentNodes.length ? dependentNodes.map((item) => <button key={item.id} onClick={() => openUnit(item.paperId, item.nodeId)}><small>{item.kind}</small><span>{item.label} · {item.title}</span></button>) : <p>No audited dependents.</p>}</div></div></section>
    <section className="inspector-section"><button onClick={() => setExpanded(!expanded)} className="inspector-toggle"><span>Proof & dependencies</span><span>{expanded ? '−' : '+'}</span></button>{expanded && <div className="mt-3"><p className="mini-label">Prerequisites</p><div className="mt-1 flex flex-wrap gap-1">{node.dependencies.length ? node.dependencies.map((dependency) => <span key={dependency} className="ref-chip">{dependency}</span>) : <span className="text-[11px] text-[#758075]">No audited prerequisites.</span>}</div><p className="mini-label mt-3">Proof expansion</p>{node.proofSketch.length ? <ol className="mt-2 space-y-2">{node.proofSketch.map((step, index) => <li key={index} className="flex gap-2 text-[11px] leading-5 text-[#566256]"><span className="grid h-4 w-4 flex-none place-items-center rounded-full bg-white text-[9px] font-bold text-[#3d7057]">{index + 1}</span>{step}</li>)}</ol> : <p className="mt-2 text-[11px] leading-5 text-[#758075]">No proof sketch was certified in the audit.</p>}</div>}</section>
    <section className="inspector-section"><p className="mini-label">Ask with full-paper context</p><div className="mt-2 flex gap-1.5"><input value={question} onChange={(event) => setQuestion(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') ask(); }} placeholder={`Ask about ${node.label}…`} className="min-w-0 flex-1 rounded border border-[#d5ddd4] px-2 py-1.5 text-[11px] outline-none" /><button onClick={ask} disabled={asking || !question.trim()} className="rounded bg-[#2d654f] px-2 text-[10px] font-bold text-white disabled:opacity-50">{asking ? '…' : 'Ask'}</button></div>{answer && <div className="mt-2 whitespace-pre-wrap rounded border border-[#dce4da] bg-white p-2.5 text-[11px] leading-5 text-[#4d5d4f]">{answer}</div>}</section>
    <section className="inspector-section"><div className="flex justify-between"><p className="mini-label">Cross-paper relations</p><span className="text-[10px] text-[#7d877d]">{edges.length}</span></div>{edges.length ? <div className="mt-2 space-y-1.5">{edges.map((edge) => { const otherId = edge.from === sourceId ? edge.to : edge.from; const other = nodeById.get(otherId); const manual = edge.source === 'manual'; const manualId = manual ? edge.id.replace('manual:', '') : ''; return <div key={edge.id} className="cross-edge"><button onClick={() => other && openUnit(other.paperId, other.nodeId)} className="min-w-0 flex-1 text-left"><b>{edge.relation}</b><span>{other ? `${other.paperTitle} · ${other.label}` : otherId}</span></button>{manual && <button onClick={() => void removeLink(manualId)} title="Remove relation" className="text-[#899189]">×</button>}</div>; })}</div> : <p className="mt-2 text-[11px] leading-5 text-[#758075]">No local cross-paper relation yet.</p>}{candidates.length > 0 && <div className="mt-3 border-t border-[#e2e7df] pt-3"><select value={target} onChange={(event) => setTarget(event.target.value)} className="w-full rounded border border-[#d5ddd4] bg-white px-2 py-1.5 text-[10px] outline-none"><option value="">Link to another audited unit…</option>{candidates.map((item) => <option key={item.id} value={item.id}>{item.paperTitle} · {item.label}</option>)}</select><div className="mt-1.5 flex gap-1.5"><select value={relation} onChange={(event) => setRelation(event.target.value as CrossLink['relation'])} className="rounded border border-[#d5ddd4] bg-white px-1.5 py-1 text-[10px]"><option value="uses">uses</option><option value="extends">extends</option><option value="background">background</option><option value="contrasts">contrasts</option></select><button onClick={createLink} disabled={!target} className="rounded border border-[#cbdacb] px-2 py-1 text-[10px] font-bold text-[#35624b] disabled:opacity-50">Add relation</button></div><input value={linkNote} onChange={(event) => setLinkNote(event.target.value)} placeholder="Optional rationale" className="mt-1.5 w-full rounded border border-[#d5ddd4] px-2 py-1.5 text-[10px] outline-none" /></div>}</section>
    <section className="inspector-section"><p className="mini-label">Your reader layer</p><textarea value={readerNote} onChange={(event) => setReaderNote(event.target.value)} placeholder="Interpretation, caveat, or alternate proof route…" className="mt-2 block min-h-16 w-full rounded border border-[#d5ddd4] p-2 text-[11px] leading-5 outline-none" /></section>
    <section className="inspector-section"><p className="mini-label">Linked LaTeX note</p><textarea value={noteText} onChange={(event) => setNoteText(event.target.value)} placeholder="Capture a derivation or question…" className="mt-2 block min-h-14 w-full rounded border border-[#d5ddd4] p-2 text-[11px] leading-5 outline-none" /><input value={noteLatex} onChange={(event) => setNoteLatex(event.target.value)} placeholder="LaTeX, e.g. \\|u\\|_{H^1} \\le C" className="mt-1.5 block w-full rounded border border-[#d5ddd4] px-2 py-1.5 text-[10px] outline-none" />{noteLatex && <div className="mt-2 rounded bg-[#f4f6f2] p-1.5"><Latex value={noteLatex} small /></div>}<button onClick={saveLinkedNote} disabled={!noteText.trim()} className="mt-2 rounded bg-[#2d654f] px-2.5 py-1.5 text-[10px] font-bold text-white disabled:opacity-50">Save note</button></section>
  </div>;
}

function Info({ label, text }: { label: string; text: string }) { return <div className="rounded border border-[#e2e7df] bg-[#fbfcfa] p-2.5"><p className="mini-label">{label}</p><p className="mt-1 text-[11px] leading-5 text-[#586458]">{text}</p></div>; }

function Library({ papers, audits, patches, busyId, analyze, updatePaper, removePaper, openUnit, openImport }: { papers: Paper[]; audits: Record<string, PaperAudit>; patches: Record<string, WorkingPatch[]>; busyId: string | null; analyze: (paper: Paper) => Promise<void>; updatePaper: (paper: Paper) => Promise<void>; removePaper: (paperId: string) => Promise<void>; openUnit: (paperId: string, nodeId: string) => void; openImport: () => void }) {
  const [query, setQuery] = useState(''); const [editing, setEditing] = useState<Paper | null>(null); const [confirming, setConfirming] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const visible = useMemo(() => { const needle = query.trim().toLowerCase(); if (!needle) return papers; return papers.filter((paper) => [paper.title, paper.authors, paper.arxivId, paper.category, paper.state, ...paper.tags].join(' ').toLowerCase().includes(needle)); }, [papers, query]);
  async function saveEdit() { if (!editing?.title.trim()) return; setSaving(true); setError(''); try { await updatePaper(editing); setEditing(null); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not update this paper.'); } finally { setSaving(false); } }
  async function remove(id: string) { setSaving(true); setError(''); try { await removePaper(id); setConfirming(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not remove this paper.'); } finally { setSaving(false); } }
  return <div className="mx-auto max-w-6xl p-6 sm:p-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="reader-kicker">Processed literature</p><h2 className="mt-1 text-3xl font-bold tracking-[-.055em]">Your local research library</h2><p className="mt-2 text-sm text-[#707970]">Search every imported paper, reopen its interactive audit, or maintain its local record.</p></div><button onClick={openImport} className="rounded-md bg-[#2d654f] px-3 py-2 text-xs font-bold text-white">+ Import paper</button></div>
    <div className="library-search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title, author, arXiv ID, field, tag, or reading state…" /><b>{visible.length} of {papers.length}</b></div>{error && <p className="library-error">{error}</p>}
    <div className="library-grid">{visible.map((paper) => <article key={paper.id} className="library-paper"><div className="library-paper-top"><div className="flex flex-wrap gap-1"><span>{paper.category}</span><span>{paper.state}</span>{(patches[paper.id]?.length ?? 0) > 0 && <span>{patches[paper.id].length} working change{patches[paper.id].length === 1 ? '' : 's'}</span>}</div><span className={audits[paper.id] ? 'library-audited' : 'library-pending'}>{audits[paper.id] ? `${audits[paper.id].nodes.length} audited units` : 'Not audited'}</span></div><h3>{paper.title}</h3><p>{paper.authors}</p><small>arXiv:{paper.arxivId}</small><div className="library-tags">{paper.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="library-paper-actions"><button onClick={() => openUnit(paper.id, audits[paper.id]?.nodes[0]?.id ?? '')}>Open reader</button><button onClick={() => void analyze(paper)} disabled={busyId === paper.id}>{busyId === paper.id ? 'Auditing…' : audits[paper.id] ? 'Re-audit' : 'Analyze'}</button><button onClick={() => { setEditing({ ...paper }); setError(''); }}>Edit record</button>{confirming === paper.id ? <button className="library-confirm-delete" onClick={() => void remove(paper.id)} disabled={saving}>Confirm remove</button> : <button className="library-remove" onClick={() => setConfirming(paper.id)}>Remove</button>}</div></article>)}</div>
    {!visible.length && <div className="library-empty">No processed paper matches “{query}”. Try an author, theorem area, arXiv ID, or tag.</div>}
    {editing && <div className="edition-overlay" onMouseDown={(event) => { if (event.currentTarget === event.target) setEditing(null); }}><section className="paper-record-editor"><header><div><p className="reader-kicker">Local library record</p><h3>Edit paper</h3></div><button onClick={() => setEditing(null)}>×</button></header><div className="paper-record-fields"><label><span>Title</span><input value={editing.title} onChange={(event) => setEditing({ ...editing, title: event.target.value })} /></label><label><span>Authors</span><input value={editing.authors} onChange={(event) => setEditing({ ...editing, authors: event.target.value })} /></label><div className="paper-record-row"><label><span>Field</span><input value={editing.category} onChange={(event) => setEditing({ ...editing, category: event.target.value })} /></label><label><span>Reading state</span><select value={editing.state} onChange={(event) => setEditing({ ...editing, state: event.target.value as Paper['state'] })}><option>To read</option><option>Reading</option><option>Read</option></select></label></div><label><span>Tags — separated by commas</span><input value={editing.tags.join(', ')} onChange={(event) => setEditing({ ...editing, tags: event.target.value.split(',').map((item) => item.trim()).filter(Boolean) })} /></label><label><span>Abstract</span><textarea value={editing.abstract} onChange={(event) => setEditing({ ...editing, abstract: event.target.value })} /></label><p>arXiv:{editing.arxivId} · The source identity and original audit remain unchanged.</p></div><footer><button onClick={() => setEditing(null)}>Cancel</button><button className="paper-record-save" onClick={() => void saveEdit()} disabled={saving || !editing.title.trim()}>{saving ? 'Saving…' : 'Save record'}</button></footer></section></div>}
  </div>;
}

function GraphView({ graph, papers, openUnit }: { graph: Graph; papers: Paper[]; openUnit: (paperId: string, nodeId: string) => void }) { const nodeById = new Map(graph.nodes.map((item) => [item.id, item])); const cross = graph.edges.filter((edge) => nodeById.get(edge.from)?.paperId !== nodeById.get(edge.to)?.paperId); return <div className="mx-auto max-w-6xl p-6 sm:p-10"><div><p className="reader-kicker">Local dependency graph</p><h2 className="mt-1 text-3xl font-bold tracking-[-.055em]">Results that travel between papers</h2><p className="mt-2 text-sm text-[#707970]">Audited units are nodes. Arrows are proof dependencies or explicit relations you add while reading.</p></div>{graph.nodes.length === 0 ? <div className="mt-8 rounded-xl border border-dashed border-[#d8dfd7] p-8 text-sm text-[#7a837a]">Audit at least one paper to build its local graph.</div> : <><div className="graph-canvas mt-8">{papers.filter((paper) => graph.nodes.some((node) => node.paperId === paper.id)).map((paper) => <section key={paper.id} className="graph-paper"><div className="flex items-center justify-between"><b>{paper.title}</b><span>{graph.nodes.filter((node) => node.paperId === paper.id).length} units</span></div><div className="mt-3 flex flex-wrap gap-2">{graph.nodes.filter((node) => node.paperId === paper.id).map((node) => <button key={node.id} onClick={() => openUnit(node.paperId, node.nodeId)} className={`graph-node ${kindClass(node.kind)}`}>{node.label}</button>)}</div></section>)}</div><section className="mt-7 rounded-xl border border-[#e0e6df] bg-white p-4"><div className="flex justify-between"><div><p className="reader-kicker">Cross-paper arrows</p><h3 className="mt-1 text-lg font-bold">{cross.length} relation{cross.length === 1 ? '' : 's'}</h3></div><span className="text-[10px] text-[#7c857c]">Add relations from a unit inspector</span></div><div className="mt-4 space-y-2">{cross.length ? cross.map((edge) => { const from = nodeById.get(edge.from); const to = nodeById.get(edge.to); return <div key={edge.id} className="graph-edge"><button onClick={() => from && openUnit(from.paperId, from.nodeId)}>{from ? `${from.paperTitle} · ${from.label}` : edge.from}</button><span>— {edge.relation} →</span><button onClick={() => to && openUnit(to.paperId, to.nodeId)}>{to ? `${to.paperTitle} · ${to.label}` : edge.to}</button>{edge.note && <small>{edge.note}</small>}</div>; }) : <p className="text-sm text-[#788178]">No cross-paper arrows yet. Link a theorem, definition, or external result from the right-hand reader inspector.</p>}</div></section></>}</div>; }

function Discover({ papers, saved, save, refresh, loading }: { papers: Paper[]; saved: Paper[]; save: (paper: Paper) => Promise<void>; refresh: () => Promise<void>; loading: boolean }) { return <div className="mx-auto max-w-5xl p-6 sm:p-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="reader-kicker">Daily discovery</p><h2 className="mt-1 text-3xl font-bold tracking-[-.055em]">Relevant papers today</h2><p className="mt-2 text-sm text-[#707970]">A lightweight arXiv feed for your selected mathematical area.</p></div><button onClick={() => void refresh()} className="rounded-md border border-[#d8e0d7] bg-white px-3 py-2 text-xs font-bold text-[#436150]">{loading ? 'Refreshing…' : 'Refresh arXiv'}</button></div><div className="mt-8 space-y-3">{papers.map((paper) => { const inVault = saved.some((item) => item.arxivId === paper.arxivId); return <article key={paper.arxivId} className="rounded-xl border border-[#e1e6df] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="max-w-2xl"><span className="rounded bg-[#edf4ee] px-2 py-1 text-[10px] font-bold text-[#46705a]">{paper.category}</span><h3 className="mt-3 text-lg font-bold">{paper.title}</h3><p className="mt-1 text-xs text-[#737c73]">{paper.authors} · arXiv:{paper.arxivId}</p><p className="mt-3 text-sm leading-6 text-[#606a60]">{paper.abstract}</p></div><button disabled={inVault} onClick={() => void save(paper)} className={`rounded-md px-3 py-2 text-xs font-bold ${inVault ? 'bg-[#edf0ec] text-[#869086]' : 'bg-[#2d654f] text-white'}`}>{inVault ? 'In vault' : '+ Save paper'}</button></div></article>; })}</div></div>; }

function Notes({ notes, papers, openUnit }: { notes: Note[]; papers: Paper[]; openUnit: (paperId: string, nodeId: string) => void }) { return <div className="mx-auto max-w-4xl p-6 sm:p-10"><p className="reader-kicker">Knowledge you keep</p><h2 className="mt-1 text-3xl font-bold tracking-[-.055em]">Linked notes</h2><p className="mt-2 text-sm text-[#707970]">Notes live with their paper, not in an unstructured notebook.</p><div className="mt-8 space-y-3">{notes.length ? notes.map((note) => { const paper = papers.find((item) => item.id === note.paperId); return <article key={note.id} className="rounded-xl border border-[#e1e6df] bg-white p-5"><div className="flex justify-between gap-3"><div><b className="text-sm">{note.anchor}</b><p className="mt-2 text-sm leading-6 text-[#596359]">{note.text}</p>{note.latex && <div className="mt-3 rounded bg-[#f4f6f2] p-2"><Latex value={note.latex} small /></div>}</div><button onClick={() => openUnit(note.paperId, note.nodeId)} className="shrink-0 text-xs font-bold text-[#2d654f]">{paper?.title ?? 'Open paper'} →</button></div></article>; }) : <div className="rounded-xl border border-dashed border-[#d8dfd7] p-8 text-center text-sm text-[#7a837a]">No notes yet. Select a theorem, definition, or proof unit to add one.</div>}</div></div>; }

function Settings({ profile, setProfile, bridge, vaultReady, refresh, paperCount }: { profile: Profile; setProfile: (value: Profile | ((old: Profile) => Profile)) => void; bridge: Bridge | null; vaultReady: boolean; refresh: () => Promise<void>; paperCount: number }) { const update = (key: keyof Profile, value: string) => setProfile((current) => ({ ...current, [key]: value })); const model = bridge?.models.find((item) => item.id === profile.model); const efforts = model?.efforts.length ? model.efforts : ['low', 'medium', 'high']; return <div className="mx-auto max-w-3xl p-6 sm:p-10"><p className="reader-kicker">Preferences</p><h2 className="mt-1 text-3xl font-bold tracking-[-.055em]">Reader & local Codex</h2><p className="mt-2 text-sm text-[#707970]">Your background steers audits; model and effort are sent only to your local Codex app-server.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><Select label="Background" value={profile.level} options={['Undergraduate', 'Graduate student', 'Researcher']} onChange={(value) => update('level', value)} /><Select label="Primary area" value={profile.area} options={['math.AG', 'math.AP', 'math.DG', 'math.PR', 'math.OC']} onChange={(value) => update('area', value)} /><Select label="Reading goal" value={profile.goal} options={['Survey new work', 'Understand proofs', 'Apply a result', 'Reproduce a proof']} onChange={(value) => update('goal', value)} /><Select label="Codex model" value={profile.model} options={(bridge?.models ?? []).map((item) => item.id)} labels={(bridge?.models ?? []).reduce<Record<string, string>>((result, item) => ({ ...result, [item.id]: item.label }), {})} onChange={(value) => update('model', value)} emptyLabel="Codex default" /><Select label="Reasoning effort" value={profile.reasoning} options={efforts} onChange={(value) => update('reasoning', value)} /></div><div className={`mt-5 rounded-xl border p-4 text-xs leading-5 ${bridge?.account ? 'border-[#dce7dd] bg-[#eff6f0] text-[#52705e]' : 'border-[#f0ddc7] bg-[#fff8ed] text-[#825b2d]'}`}><div className="flex justify-between gap-3"><b>Local vault & Codex bridge</b><button onClick={() => void refresh()} className="rounded border border-current/20 bg-white/60 px-2 py-1 text-[10px] font-bold">Refresh</button></div><p className="mt-1">{bridge?.account ? `Connected with local ${bridge.account.type}${bridge.account.planType ? ` (${bridge.account.planType})` : ''}.` : 'Bridge not connected.'} {vaultReady ? `${paperCount} paper folder${paperCount === 1 ? '' : 's'} in the local vault.` : 'Opening local vault…'} No API key is used.</p></div></div>; }

function Select({ label, value, options, labels = {}, onChange, emptyLabel }: { label: string; value: string; options: string[]; labels?: Record<string, string>; onChange: (value: string) => void; emptyLabel?: string }) { return <label className="rounded-xl border border-[#e1e6df] bg-white p-4"><span className="text-xs font-bold">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="mt-3 block w-full rounded-md border border-[#dce3da] bg-[#fbfcf9] px-2.5 py-2 text-xs text-[#415c4b] outline-none"><option value="">{emptyLabel ?? 'Codex default'}</option>{options.map((option) => <option key={option} value={option}>{labels[option] ?? option}</option>)}</select></label>; }

function ImportDialog({ close, importArxiv }: { close: () => void; importArxiv: (value: string) => Promise<void> }) { const [value, setValue] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); async function submit(event: FormEvent) { event.preventDefault(); if (!value.trim()) return; setBusy(true); setError(''); try { await importArxiv(value); } catch (cause) { setError(cause instanceof Error ? cause.message : 'The paper could not be imported.'); } finally { setBusy(false); } } return <div className="fixed inset-0 z-30 grid place-items-center bg-[#18261e]/35 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="reader-kicker">ArXiv to paper vault</p><h2 className="mt-1 text-xl font-bold">Import & audit a paper</h2></div><button type="button" onClick={close} className="text-lg text-[#788078]">×</button></div><p className="mt-3 text-xs leading-5 text-[#737c73]">Paste an arXiv ID, abstract URL, or PDF URL. Proofroom creates a stable local folder, then asks your local Codex subscription to audit the primary source.</p><label className="mt-5 block"><span className="text-xs font-bold">arXiv ID or URL</span><input autoFocus value={value} onChange={(event) => setValue(event.target.value)} placeholder="e.g. 2608.04121 or https://arxiv.org/abs/2608.04121" className="mt-1.5 block w-full rounded-md border border-[#dce3da] px-3 py-2.5 text-xs outline-none" /></label>{error && <p className="mt-3 rounded-md bg-[#fff1ed] p-2.5 text-xs text-[#a34c3a]">{error}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={close} className="rounded-md px-3 py-2 text-xs text-[#697369]">Cancel</button><button disabled={busy} className="rounded-md bg-[#2d654f] px-3 py-2 text-xs font-bold text-white disabled:opacity-60">{busy ? 'Importing & auditing…' : 'Import & analyze'}</button></div></form></div>; }
